/*
 * Closure Library
 * This product includes Closure Library (https://developers.google.com/closure/library/).
 * Licensed under the Apache License, Version 2.0.
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * # This is a list of contributors to the Closure Library.
 * Google Inc.
 * Mohamed Mansour <hello@mohamedmansour.com>
 * Bjorn Tipling <bjorn.tipling@gmail.com>
 * SameGoal LLC <help@samegoal.com>
 * Guido Tapia <guido.tapia@gmail.com>
 * Andrew Mattie <amattie@gmail.com>
 * Ilia Mirkin <ibmirkin@gmail.com>
 * Ivan Kozik <ivan.kozik@gmail.com>
 * Rich Dougherty <rich@rd.gen.nz>
 * Chad Killingsworth <chadkillingsworth@missouristate.edu>
 * Dan Pupius <dan.pupius@gmail.com>
*/
(function(){function g(a){throw a;}var k=void 0,l=!0,n=null,p=!1;function aa(a){return function(){return this[a]}}var r,t=this;function ba(){}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function da(a){return"array"==ca(a)}function ea(a){var b=ca(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"function"==ca(a)}function fa(a){a=ca(a);return"object"==a||"array"==a||"function"==a}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){a||g(Error());if(2<arguments.length){var f=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,f);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){la=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return la.apply(n,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var na=Date.now||function(){return+new Date};function z(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c};var A={ma:["BC","AD"],Ca:["Before Christ","Anno Domini"],Da:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),Fa:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),I:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),Ea:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),qa:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),Ha:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),sa:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),
Ja:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),Y:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),Ia:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),Wa:"S,M,T,W,T,F,S".split(","),Ga:"S,M,T,W,T,F,S".split(","),ra:["Q1","Q2","Q3","Q4"],pa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],la:["AM","PM"],N:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],T:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],na:6,ta:[5,6],oa:2},oa={ma:["\u7d00\u5143\u524d","\u897f\u66a6"],Ca:["\u7d00\u5143\u524d",
"\u897f\u66a6"],Da:"1,2,3,4,5,6,7,8,9,10,11,12".split(","),Fa:"1,2,3,4,5,6,7,8,9,10,11,12".split(","),I:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),Ea:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),qa:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),Ha:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),
sa:"\u65e5\u66dc\u65e5,\u6708\u66dc\u65e5,\u706b\u66dc\u65e5,\u6c34\u66dc\u65e5,\u6728\u66dc\u65e5,\u91d1\u66dc\u65e5,\u571f\u66dc\u65e5".split(","),Ja:"\u65e5\u66dc\u65e5,\u6708\u66dc\u65e5,\u706b\u66dc\u65e5,\u6c34\u66dc\u65e5,\u6728\u66dc\u65e5,\u91d1\u66dc\u65e5,\u571f\u66dc\u65e5".split(","),Y:"\u65e5,\u6708,\u706b,\u6c34,\u6728,\u91d1,\u571f".split(","),Ia:"\u65e5,\u6708,\u706b,\u6c34,\u6728,\u91d1,\u571f".split(","),Wa:"\u65e5,\u6708,\u706b,\u6c34,\u6728,\u91d1,\u571f".split(","),Ga:"\u65e5,\u6708,\u706b,\u6c34,\u6728,\u91d1,\u571f".split(","),
ra:["Q1","Q2","Q3","Q4"],pa:["\u7b2c1\u56db\u534a\u671f","\u7b2c2\u56db\u534a\u671f","\u7b2c3\u56db\u534a\u671f","\u7b2c4\u56db\u534a\u671f"],la:["\u5348\u524d","\u5348\u5f8c"],N:["y\u5e74M\u6708d\u65e5EEEE","y\u5e74M\u6708d\u65e5","yyyy/MM/dd","yy/MM/dd"],T:["H\u6642mm\u5206ss\u79d2 zzzz","H:mm:ss z","H:mm:ss","H:mm"],na:6,ta:[5,6],oa:2},pa={ma:["\u516c\u5143\u524d","\u516c\u5143"],Ca:["\u516c\u5143\u524d","\u516c\u5143"],Da:"1,2,3,4,5,6,7,8,9,10,11,12".split(","),Fa:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),
I:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),Ea:"\u4e00\u6708,\u4e8c\u6708,\u4e09\u6708,\u56db\u6708,\u4e94\u6708,\u516d\u6708,\u4e03\u6708,\u516b\u6708,\u4e5d\u6708,\u5341\u6708,\u5341\u4e00\u6708,\u5341\u4e8c\u6708".split(","),qa:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),Ha:"\u4e00\u6708,\u4e8c\u6708,\u4e09\u6708,\u56db\u6708,\u4e94\u6708,\u516d\u6708,\u4e03\u6708,\u516b\u6708,\u4e5d\u6708,\u5341\u6708,\u5341\u4e00\u6708,\u5341\u4e8c\u6708".split(","),
sa:"\u661f\u671f\u65e5,\u661f\u671f\u4e00,\u661f\u671f\u4e8c,\u661f\u671f\u4e09,\u661f\u671f\u56db,\u661f\u671f\u4e94,\u661f\u671f\u516d".split(","),Ja:"\u661f\u671f\u65e5,\u661f\u671f\u4e00,\u661f\u671f\u4e8c,\u661f\u671f\u4e09,\u661f\u671f\u56db,\u661f\u671f\u4e94,\u661f\u671f\u516d".split(","),Y:"\u5468\u65e5,\u5468\u4e00,\u5468\u4e8c,\u5468\u4e09,\u5468\u56db,\u5468\u4e94,\u5468\u516d".split(","),Ia:"\u5468\u65e5,\u5468\u4e00,\u5468\u4e8c,\u5468\u4e09,\u5468\u56db,\u5468\u4e94,\u5468\u516d".split(","),
Wa:"\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(","),Ga:"\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(","),ra:["1\u5b63","2\u5b63","3\u5b63","4\u5b63"],pa:["\u7b2c1\u5b63\u5ea6","\u7b2c2\u5b63\u5ea6","\u7b2c3\u5b63\u5ea6","\u7b2c4\u5b63\u5ea6"],la:["\u4e0a\u5348","\u4e0b\u5348"],N:["y\u5e74M\u6708d\u65e5EEEE","y\u5e74M\u6708d\u65e5","yyyy-M-d","yy-M-d"],T:["zzzzah\u65f6mm\u5206ss\u79d2","zah\u65f6mm\u5206ss\u79d2","ah:mm:ss","ah:mm"],na:6,ta:[5,6],oa:2},qa={ma:["\u897f\u5143\u524d",
"\u897f\u5143"],Ca:["\u897f\u5143\u524d","\u897f\u5143"],Da:"1,2,3,4,5,6,7,8,9,10,11,12".split(","),Fa:"1,2,3,4,5,6,7,8,9,10,11,12".split(","),I:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),Ea:"\u4e00\u6708,\u4e8c\u6708,\u4e09\u6708,\u56db\u6708,\u4e94\u6708,\u516d\u6708,\u4e03\u6708,\u516b\u6708,\u4e5d\u6708,\u5341\u6708,\u5341\u4e00\u6708,\u5341\u4e8c\u6708".split(","),qa:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),
Ha:"1\u6708,2\u6708,3\u6708,4\u6708,5\u6708,6\u6708,7\u6708,8\u6708,9\u6708,10\u6708,11\u6708,12\u6708".split(","),sa:"\u661f\u671f\u65e5,\u661f\u671f\u4e00,\u661f\u671f\u4e8c,\u661f\u671f\u4e09,\u661f\u671f\u56db,\u661f\u671f\u4e94,\u661f\u671f\u516d".split(","),Ja:"\u661f\u671f\u65e5,\u661f\u671f\u4e00,\u661f\u671f\u4e8c,\u661f\u671f\u4e09,\u661f\u671f\u56db,\u661f\u671f\u4e94,\u661f\u671f\u516d".split(","),Y:"\u9031\u65e5,\u9031\u4e00,\u9031\u4e8c,\u9031\u4e09,\u9031\u56db,\u9031\u4e94,\u9031\u516d".split(","),
Ia:"\u5468\u65e5,\u5468\u4e00,\u5468\u4e8c,\u5468\u4e09,\u5468\u56db,\u5468\u4e94,\u5468\u516d".split(","),Wa:"\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(","),Ga:"\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(","),ra:["1\u5b63","2\u5b63","3\u5b63","4\u5b63"],pa:["\u7b2c1\u5b63","\u7b2c2\u5b63","\u7b2c3\u5b63","\u7b2c4\u5b63"],la:["\u4e0a\u5348","\u4e0b\u5348"],N:["y\u5e74M\u6708d\u65e5EEEE","y\u5e74M\u6708d\u65e5","yyyy/M/d","yy/M/d"],T:["zzzzah\u6642mm\u5206ss\u79d2","zah\u6642mm\u5206ss\u79d2",
"ah:mm:ss","ah:mm"],na:6,ta:[5,6],oa:2};function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function sa(a){if(!ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ua,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(va,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(xa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ya,"&quot;"));return a}var ua=/&/g,va=/</g,xa=/>/g,ya=/\"/g,ta=/[&<>\"]/;function B(a,b){var c=""+a,f=c.indexOf(".");if(-1==f)f=c.length;f=Math.max(0,b-f);return Array(f+1).join("0")+c};var za,Aa,Ba,Ca,Da,Ea;function Fa(){return t.navigator?t.navigator.userAgent:n}function Ga(){return t.navigator}Da=Ca=Ba=Aa=za=p;var Ha;if(Ha=Fa()){var Ia=Ga();za=0==Ha.indexOf("Opera");Aa=!za&&-1!=Ha.indexOf("MSIE");Ca=(Ba=!za&&-1!=Ha.indexOf("WebKit"))&&-1!=Ha.indexOf("Mobile");Da=!za&&!Ba&&"Gecko"==Ia.product}var Ja=za,C=Aa,D=Da,E=Ba,Ka=Ca,La=Ga();Ea=-1!=(La&&La.platform||"").indexOf("Mac");var Ma=!!Ga()&&-1!=(Ga().appVersion||"").indexOf("X11"),Na;
a:{var Oa="",Pa;if(Ja&&t.opera)var Qa=t.opera.version,Oa="function"==typeof Qa?Qa():Qa;else if(D?Pa=/rv\:([^\);]+)(\)|;)/:C?Pa=/MSIE\s+([^\);]+)(\)|;)/:E&&(Pa=/WebKit\/(\S+)/),Pa)var Ra=Pa.exec(Fa()),Oa=Ra?Ra[1]:"";if(C){var Sa,Ta=t.document;Sa=Ta?Ta.documentMode:k;if(Sa>parseFloat(Oa)){Na=""+Sa;break a}}Na=Oa}var Ua={};
function F(a){var b;if(!(b=Ua[a])){b=0;for(var c=ra(""+Na).split("."),f=ra(""+a).split("."),d=Math.max(c.length,f.length),e=0;0==b&&e<d;e++){var h=c[e]||"",i=f[e]||"",j=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var q=j.exec(h)||["","",""],s=m.exec(i)||["","",""];if(0==q[0].length&&0==s[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==s[1].length?0:parseInt(s[1],10))?-1:(0==q[1].length?0:parseInt(q[1],10))>(0==s[1].length?0:parseInt(s[1],10))?1:0)||((0==q[2].length)<(0==
s[2].length)?-1:(0==q[2].length)>(0==s[2].length)?1:0)||(q[2]<s[2]?-1:q[2]>s[2]?1:0)}while(0==b)}b=Ua[a]=0<=b}return b}var Va={};function Wa(){return Va[9]||(Va[9]=C&&document.documentMode&&9<=document.documentMode)};function Xa(){}var Ya=0;r=Xa.prototype;r.key=0;r.X=p;r.$a=p;r.xa=function(a,b,c,f,d,e){v(a)?this.Kb=l:a&&a.handleEvent&&v(a.handleEvent)?this.Kb=p:g(Error("Invalid listener argument"));this.ha=a;this.Tb=b;this.src=c;this.type=f;this.capture=!!d;this.Ma=e;this.$a=p;this.key=++Ya;this.X=p};r.handleEvent=function(a){return this.Kb?this.ha.call(this.Ma||this.src,a):this.ha.handleEvent.call(this.ha,a)};function ab(a,b){for(var c in a)b.call(k,a[c],c,a)}var bb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function cb(a,b){for(var c,f,d=1;d<arguments.length;d++){f=arguments[d];for(c in f)a[c]=f[c];for(var e=0;e<bb.length;e++)c=bb[e],Object.prototype.hasOwnProperty.call(f,c)&&(a[c]=f[c])}};!C||Wa();var db=!C||Wa(),eb=C&&!F("8");var G=Array.prototype,fb=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},gb=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var f=a.length,d=u(a)?a.split(""):a,e=0;e<f;e++)e in d&&b.call(c,d[e],e,a)};function hb(a,b){var c=fb(a,b);0<=c&&G.splice.call(a,c,1)}
function ib(a){return G.concat.apply(G,arguments)}function jb(a){if(da(a))return ib(a);for(var b=[],c=0,f=a.length;c<f;c++)b[c]=a[c];return b}function kb(a,b,c,f){G.splice.apply(a,lb(arguments,1))}function lb(a,b,c){return 2>=arguments.length?G.slice.call(a,b):G.slice.call(a,b,c)};function mb(){}mb.prototype.Cb=p;mb.prototype.u=function(){if(!this.Cb)this.Cb=l,this.j()};mb.prototype.j=function(){this.fc&&nb.apply(n,this.fc)};function ob(a){a&&"function"==typeof a.u&&a.u()}function nb(a){for(var b=0,c=arguments.length;b<c;++b){var f=arguments[b];ea(f)?nb.apply(n,f):ob(f)}};function H(a,b){this.type=a;this.currentTarget=this.target=b}z(H,mb);r=H.prototype;r.j=function(){delete this.type;delete this.target;delete this.currentTarget};r.W=p;r.za=l;r.stopPropagation=function(){this.W=l};r.preventDefault=function(){this.za=p};function pb(a){pb[" "](a);return a}pb[" "]=ba;function qb(a,b){a&&this.xa(a,b)}z(qb,H);r=qb.prototype;r.target=n;r.relatedTarget=n;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=p;r.altKey=p;r.shiftKey=p;r.metaKey=p;r.xc=p;r.F=n;
r.xa=function(a,b){var c=this.type=a.type;H.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var f=a.relatedTarget;if(f){if(D){var d;a:{try{pb(f.nodeName);d=l;break a}catch(e){}d=p}d||(f=n)}}else if("mouseover"==c)f=a.fromElement;else if("mouseout"==c)f=a.toElement;this.relatedTarget=f;this.offsetX=a.offsetX!==k?a.offsetX:a.layerX;this.offsetY=a.offsetY!==k?a.offsetY:a.layerY;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.xc=Ea?a.metaKey:a.ctrlKey;this.state=a.state;this.F=a;delete this.za;delete this.W};r.stopPropagation=function(){qb.h.stopPropagation.call(this);this.F.stopPropagation?this.F.stopPropagation():this.F.cancelBubble=l};
r.preventDefault=function(){qb.h.preventDefault.call(this);var a=this.F;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,eb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};r.ic=aa("F");r.j=function(){qb.h.j.call(this);this.relatedTarget=this.currentTarget=this.target=this.F=n};var rb={},I={},J={},sb={};
function tb(a,b,c,f,d){if(b){if(da(b)){for(var e=0;e<b.length;e++)tb(a,b[e],c,f,d);return n}var f=!!f,h=I;b in h||(h[b]={z:0,w:0});h=h[b];f in h||(h[f]={z:0,w:0},h.z++);var h=h[f],i=ga(a),j;h.w++;if(h[i]){j=h[i];for(e=0;e<j.length;e++)if(h=j[e],h.ha==c&&h.Ma==d){if(h.X)break;return j[e].key}}else j=h[i]=[],h.z++;e=ub();e.src=a;h=new Xa;h.xa(c,e,a,b,f,d);c=h.key;e.key=c;j.push(h);rb[c]=h;J[i]||(J[i]=[]);J[i].push(h);a.addEventListener?(a==t||!a.xb)&&a.addEventListener(b,e,f):a.attachEvent(b in sb?
sb[b]:sb[b]="on"+b,e);return c}g(Error("Invalid event type"))}function ub(){var a=vb,b=db?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function wb(a,b,c,f,d){if(da(b))for(var e=0;e<b.length;e++)wb(a,b[e],c,f,d);else a=tb(a,b,c,f,d),rb[a].$a=l}function xb(a,b,c,f,d){if(da(b))for(var e=0;e<b.length;e++)xb(a,b[e],c,f,d);else if(f=!!f,a=zb(a,b,f))for(e=0;e<a.length;e++)if(a[e].ha==c&&a[e].capture==f&&a[e].Ma==d){K(a[e].key);break}}
function K(a){if(!rb[a])return p;var b=rb[a];if(b.X)return p;var c=b.src,f=b.type,d=b.Tb,e=b.capture;c.removeEventListener?(c==t||!c.xb)&&c.removeEventListener(f,d,e):c.detachEvent&&c.detachEvent(f in sb?sb[f]:sb[f]="on"+f,d);c=ga(c);d=I[f][e][c];if(J[c]){var h=J[c];hb(h,b);0==h.length&&delete J[c]}b.X=l;d.Mb=l;Ab(f,e,c,d);delete rb[a];return l}
function Ab(a,b,c,f){if(!f.Ra&&f.Mb){for(var d=0,e=0;d<f.length;d++)f[d].X?f[d].Tb.src=n:(d!=e&&(f[e]=f[d]),e++);f.length=e;f.Mb=p;0==e&&(delete I[a][b][c],I[a][b].z--,0==I[a][b].z&&(delete I[a][b],I[a].z--),0==I[a].z&&delete I[a])}}function Bb(a){var b,c=0,f=b==n;b=!!b;if(a==n)ab(J,function(a){for(var d=a.length-1;0<=d;d--){var e=a[d];if(f||b==e.capture)K(e.key),c++}});else if(a=ga(a),J[a])for(var a=J[a],d=a.length-1;0<=d;d--){var e=a[d];if(f||b==e.capture)K(e.key),c++}}
function zb(a,b,c){var f=I;return b in f&&(f=f[b],c in f&&(f=f[c],a=ga(a),f[a]))?f[a]:n}function Cb(a,b,c,f,d){var e=1,b=ga(b);if(a[b]){a.w--;a=a[b];a.Ra?a.Ra++:a.Ra=1;try{for(var h=a.length,i=0;i<h;i++){var j=a[i];j&&!j.X&&(e&=Db(j,d)!==p)}}finally{a.Ra--,Ab(c,f,b,a)}}return Boolean(e)}function Db(a,b){var c=a.handleEvent(b);a.$a&&K(a.key);return c}
function vb(a,b){if(!rb[a])return l;var c=rb[a],f=c.type,d=I;if(!(f in d))return l;var d=d[f],e,h;if(!db){var i;if(!(i=b))a:{i="window.event".split(".");for(var j=t;e=i.shift();)if(j[e]!=n)j=j[e];else{i=n;break a}i=j}e=i;i=l in d;j=p in d;if(i){if(0>e.keyCode||e.returnValue!=k)return l;a:{var m=p;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(q){m=l}if(m||e.returnValue==k)e.returnValue=l}}m=new qb;m.xa(e,this);e=l;try{if(i){for(var s=[],x=m.currentTarget;x;x=x.parentNode)s.push(x);h=d[l];h.w=h.z;
for(var w=s.length-1;!m.W&&0<=w&&h.w;w--)m.currentTarget=s[w],e&=Cb(h,s[w],f,l,m);if(j){h=d[p];h.w=h.z;for(w=0;!m.W&&w<s.length&&h.w;w++)m.currentTarget=s[w],e&=Cb(h,s[w],f,p,m)}}else e=Db(c,m)}finally{if(s)s.length=0;m.u()}return e}f=new qb(b,this);try{e=Db(c,f)}finally{f.u()}return e};function L(a,b){this.x=a!==k?a:0;this.y=b!==k?b:0}L.prototype.n=function(){return new L(this.x,this.y)};L.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Eb(a,b){return new L(a.x-b.x,a.y-b.y)};function M(a,b,c,f){this.top=a;this.right=b;this.bottom=c;this.left=f}M.prototype.n=function(){return new M(this.top,this.right,this.bottom,this.left)};M.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};M.prototype.contains=function(a){return!this||!a?p:a instanceof M?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function N(a,b){this.width=a;this.height=b}N.prototype.n=function(){return new N(this.width,this.height)};N.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};N.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};N.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Fb(a,b,c,f){this.left=a;this.top=b;this.width=c;this.height=f}Fb.prototype.n=function(){return new Fb(this.left,this.top,this.width,this.height)};Fb.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
Fb.prototype.contains=function(a){return a instanceof Fb?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};var Gb;function Hb(a,b){var c;c=(c=a.className)&&"function"==typeof c.split?c.split(/\s+/):[];var f=lb(arguments,1),d;d=c;for(var e=0,h=0;h<f.length;h++)0<=fb(d,f[h])||(d.push(f[h]),e++);d=e==f.length;a.className=c.join(" ");return d};var Ib=!C||Wa();!D&&!C||C&&Wa()||D&&F("1.9.1");C&&F("9");function P(a){return a?new Jb(Q(a)):Gb||(Gb=new Jb)}function Kb(a,b){ab(b,function(b,f){"style"==f?a.style.cssText=b:"class"==f?a.className=b:"for"==f?a.htmlFor=b:f in Lb?a.setAttribute(Lb[f],b):0==f.lastIndexOf("aria-",0)?a.setAttribute(f,b):a[f]=b})}var Lb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Mb(a,b,c){function f(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(var d=2;d<c.length;d++){var e=c[d];ea(e)&&!(fa(e)&&0<e.nodeType)?gb(Nb(e)?jb(e):e,f):f(e)}}function Ob(a){return"CSS1Compat"==a.compatMode}function Pb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Qb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function Rb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}
function Sb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Tb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else Pb(a),a.appendChild(Q(a).createTextNode(b))}function Nb(a){if(a&&"number"==typeof a.length){if(fa(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return p}function Jb(a){this.e=a||t.document||document}r=Jb.prototype;r.gb=P;function Ub(a){return a.e}
r.i=function(a){return u(a)?this.e.getElementById(a):a};r.C=function(a,b,c){var f=this.e,d=arguments,e=d[0],h=d[1];if(!Ib&&h&&(h.name||h.type)){e=["<",e];h.name&&e.push(' name="',sa(h.name),'"');if(h.type){e.push(' type="',sa(h.type),'"');var i={};cb(i,h);h=i;delete h.type}e.push(">");e=e.join("")}e=f.createElement(e);if(h)u(h)?e.className=h:da(h)?Hb.apply(n,[e].concat(h)):Kb(e,h);2<d.length&&Mb(f,e,d);return e};r.createElement=function(a){return this.e.createElement(a)};r.createTextNode=function(a){return this.e.createTextNode(a)};
function Vb(a){return Ob(a.e)}function Wb(a){var b=a.e,a=!E&&Ob(b)?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new L(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}r.appendChild=function(a,b){a.appendChild(b)};r.contains=Sb;function R(a,b){var c=Q(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,n))?c[b]||c.getPropertyValue(b):""}function Xb(a,b){return a.currentStyle?a.currentStyle[b]:n}function Yb(a,b){return R(a,b)||Xb(a,b)||a.style[b]}function Zb(a){var b=a.getBoundingClientRect();if(C)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;return b}
function $b(a){if(C)return a.offsetParent;for(var b=Q(a),c=Yb(a,"position"),f="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Yb(a,"position"),f=f&&"static"==c&&a!=b.documentElement&&a!=b.body,!f&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return n}
function ac(a){for(var b=new M(0,Infinity,Infinity,0),c=P(a),f=c.e.body,d=c.e.documentElement,e=!E&&Ob(c.e)?c.e.documentElement:c.e.body;a=$b(a);)if((!C||0!=a.clientWidth)&&(!E||0!=a.clientHeight||a!=f)&&a!=f&&a!=d&&"visible"!=Yb(a,"overflow")){var h=bc(a),i;i=a;if(D&&!F("1.9")){var j=parseFloat(R(i,"borderLeftWidth"));if(cc(i))var m=i.offsetWidth-i.clientWidth-j-parseFloat(R(i,"borderRightWidth")),j=j+m;i=new L(j,parseFloat(R(i,"borderTopWidth")))}else i=new L(i.clientLeft,i.clientTop);h.x+=i.x;
h.y+=i.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}f=e.scrollLeft;e=e.scrollTop;b.left=Math.max(b.left,f);b.top=Math.max(b.top,e);c=c.e.parentWindow||c.e.defaultView||window;d=c.document;E&&!F("500")&&!Ka?("undefined"==typeof c.innerHeight&&(c=window),d=c.innerHeight,a=c.document.documentElement.scrollHeight,c==c.top&&a<d&&(d-=15),c=new N(c.innerWidth,d)):(c=Ob(d)?d.documentElement:d.body,c=new N(c.clientWidth,
c.clientHeight));b.right=Math.min(b.right,f+c.width);b.bottom=Math.min(b.bottom,e+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:n}
function bc(a){var b,c=Q(a),f=Yb(a,"position"),d=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==f&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),e=new L(0,0),h;b=c?9==c.nodeType?c:Q(c):document;h=C&&!Wa()&&!Vb(P(b))?b.body:b.documentElement;if(a==h)return e;if(a.getBoundingClientRect)b=Zb(a),a=Wb(P(c)),e.x=b.left+a.x,e.y=b.top+a.y;else if(c.getBoxObjectFor&&!d)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(h),e.x=b.screenX-a.screenX,e.y=b.screenY-a.screenY;else{b=a;do{e.x+=b.offsetLeft;
e.y+=b.offsetTop;b!=a&&(e.x+=b.clientLeft||0,e.y+=b.clientTop||0);if(E&&"fixed"==Yb(b,"position")){e.x+=c.body.scrollLeft;e.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ja||E&&"absolute"==f)e.y-=c.body.offsetTop;for(b=a;(b=$b(b))&&b!=c.body&&b!=h;)if(e.x-=b.scrollLeft,!Ja||"TR"!=b.tagName)e.y-=b.scrollTop}return e}function dc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function ec(a){if("none"!=Yb(a,"display"))return fc(a);var b=a.style,c=b.display,f=b.visibility,d=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=fc(a);b.display=c;b.position=d;b.visibility=f;return a}function fc(a){var b=a.offsetWidth,c=a.offsetHeight,f=E&&!b&&!c;return(b===k||f)&&a.getBoundingClientRect?(a=Zb(a),new N(a.right-a.left,a.bottom-a.top)):new N(b,c)}function S(a,b){a.style.display=b?"":"none"}function cc(a){return"rtl"==Yb(a,"direction")}
function gc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,f=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var d=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=f;return d}var hc={thin:2,medium:4,thick:6};function ic(a,b){if("none"==Xb(a,b+"Style"))return 0;var c=Xb(a,b+"Width");return c in hc?hc[c]:gc(a,c)};function jc(){}z(jc,mb);r=jc.prototype;r.xb=l;r.Sa=n;r.nb=function(a){this.Sa=a};r.addEventListener=function(a,b,c,f){tb(this,a,b,c,f)};r.removeEventListener=function(a,b,c,f){xb(this,a,b,c,f)};
r.dispatchEvent=function(a){var b=a.type||a,c=I;if(b in c){if(u(a))a=new H(a,this);else if(a instanceof H)a.target=a.target||this;else{var f=a,a=new H(b,this);cb(a,f)}var f=1,d,c=c[b],b=l in c,e;if(b){d=[];for(e=this;e;e=e.Sa)d.push(e);e=c[l];e.w=e.z;for(var h=d.length-1;!a.W&&0<=h&&e.w;h--)a.currentTarget=d[h],f&=Cb(e,d[h],a.type,l,a)&&a.za!=p}if(p in c)if(e=c[p],e.w=e.z,b)for(h=0;!a.W&&h<d.length&&e.w;h++)a.currentTarget=d[h],f&=Cb(e,d[h],a.type,p,a)&&a.za!=p;else for(d=this;!a.W&&d&&e.w;d=d.Sa)a.currentTarget=
d,f&=Cb(e,d,a.type,p,a)&&a.za!=p;a=Boolean(f)}else a=l;return a};r.j=function(){jc.h.j.call(this);Bb(this);this.Sa=n};var kc=t.window;function lc(a){this.v=a;this.Pa=[]}z(lc,mb);var mc=[];function T(a,b,c,f,d){da(c)||(mc[0]=c,c=mc);for(var e=0;e<c.length;e++)a.Pa.push(tb(b,c[e],f||a,d||p,a.v||a))}function nc(a,b,c,f,d,e){if(da(c))for(var h=0;h<c.length;h++)nc(a,b,c[h],f,d,e);else{a:{f=f||a;e=e||a.v||a;d=!!d;if(b=zb(b,c,d))for(c=0;c<b.length;c++)if(!b[c].X&&b[c].ha==f&&b[c].capture==d&&b[c].Ma==e){b=b[c];break a}b=n}if(b)b=b.key,K(b),hb(a.Pa,b)}}function oc(a){gb(a.Pa,K);a.Pa.length=0}
lc.prototype.j=function(){lc.h.j.call(this);oc(this)};lc.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function pc(a,b,c,f,d){if(!C&&(!E||!F("525")))return l;if(Ea&&d)return qc(a);if(d&&!f||!c&&(17==b||18==b)||C&&f&&b==a)return p;switch(a){case 13:return!(C&&Wa());case 27:return!E}return qc(a)}function qc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||E&&0==a)return l;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return l;default:return p}};function rc(a,b){this.v=new lc(this);this.P&&g(Error("Can not change this state of the popup while showing."));this.b=a||n;if(b)this.ka=b}z(rc,jc);r=rc.prototype;r.b=n;r.ec=l;r.ub=n;r.P=p;r.Bc=p;r.kb=-1;r.Lb=-1;r.pc=p;r.gc=l;r.ka="toggle_display";r.i=aa("b");
function sc(a,b){a.Aa&&a.Aa.stop();a.wa&&a.wa.stop();if(b){if(!a.P&&a.dispatchEvent("beforeshow")){a.b||g(Error("Caller must call setElement before trying to show the popup"));a.L();var c=Q(a.b);a.pc&&T(a.v,c,"keydown",a.vc,l);if(a.ec)if(T(a.v,c,"mousedown",a.Pb,l),C){var f;try{f=c.activeElement}catch(d){}for(;f&&"IFRAME"==f.nodeName;){try{var e=f.contentDocument||f.contentWindow.document}catch(h){break}c=e;f=c.activeElement}T(a.v,c,"mousedown",a.Pb,l);T(a.v,c,"deactivate",a.Ob)}else T(a.v,c,"blur",
a.Ob);"toggle_display"==a.ka?(a.b.style.visibility="visible",S(a.b,l)):"move_offscreen"==a.ka&&a.L();a.P=l;a.Aa?(wb(a.Aa,"end",a.Qb,p,a),a.Aa.play()):a.Qb()}}else tc(a)}r.L=ba;function tc(a,b){if(!a.P||!a.dispatchEvent({type:"beforehide",target:b}))return p;a.v&&oc(a.v);a.wa?(wb(a.wa,"end",ma(a.wb,b),p,a),a.wa.play()):a.wb(b);return l}
r.wb=function(a){if("toggle_display"==this.ka)if(this.Bc){var b=this.Jb;v(b)?this&&(b=la(b,this)):b&&"function"==typeof b.handleEvent?b=la(b.handleEvent,b):g(Error("Invalid listener argument"));kc.setTimeout(b,0)}else this.Jb();else if("move_offscreen"==this.ka)this.b.style.left="-200px",this.b.style.top="-200px";this.P=p;this.Lb=na();this.dispatchEvent({type:"hide",target:a})};r.Jb=function(){this.b.style.visibility="hidden";S(this.b,p)};r.Qb=function(){this.kb=na();this.Lb=-1;this.dispatchEvent("show")};
r.Pb=function(a){a=a.target;!Sb(this.b,a)&&(!this.ub||Sb(this.ub,a))&&!(150>na()-this.kb)&&tc(this,a)};r.vc=function(a){27==a.keyCode&&tc(this,a.target)&&(a.preventDefault(),a.stopPropagation())};r.Ob=function(a){if(this.gc){var b=Q(this.b);if(C||Ja){if(a=b.activeElement,!a||Sb(this.b,a)||"BODY"==a.tagName)return}else if(a.target!=b)return;150>na()-this.kb||tc(this)}};r.j=function(){rc.h.j.call(this);this.v.u();ob(this.Aa);ob(this.wa);delete this.b;delete this.v};function uc(a,b,c,f,d,e,h,i){var j,m=c.offsetParent;if(m){var q="HTML"==m.tagName||"BODY"==m.tagName;if(!q||"static"!=Yb(m,"position"))j=bc(m),q||(j=Eb(j,new L(m.scrollLeft,m.scrollTop)))}m=bc(a);q=ec(a);m=new Fb(m.x,m.y,q.width,q.height);if(q=ac(a)){var s=new Fb(q.left,q.top,q.right-q.left,q.bottom-q.top),q=Math.max(m.left,s.left),x=Math.min(m.left+m.width,s.left+s.width);if(q<=x){var w=Math.max(m.top,s.top),s=Math.min(m.top+m.height,s.top+s.height);if(w<=s)m.left=q,m.top=w,m.width=x-q,m.height=
s-w}}q=P(a);w=P(c);if(q.e!=w.e){var x=q.e.body,w=w.e.parentWindow||w.e.defaultView,s=new L(0,0),wa=Q(x)?Q(x).parentWindow||Q(x).defaultView:window,yb=x;do{var O;if(wa==w)O=bc(yb);else{var y=yb;O=new L;if(1==y.nodeType)if(y.getBoundingClientRect)y=Zb(y),O.x=y.left,O.y=y.top;else{var Za=Wb(P(y)),y=bc(y);O.x=y.x-Za.x;O.y=y.y-Za.y}else{var Za=v(y.ic),$a=y;y.targetTouches?$a=y.targetTouches[0]:Za&&y.F.targetTouches&&($a=y.F.targetTouches[0]);O.x=$a.clientX;O.y=$a.clientY}}s.x+=O.x;s.y+=O.y}while(wa&&wa!=
w&&(yb=wa.frameElement)&&(wa=wa.parent));x=Eb(s,bc(x));C&&!Vb(q)&&(x=Eb(x,Wb(q)));m.left+=x.x;m.top+=x.y}a=(b&4&&cc(a)?b^2:b)&-5;b=new L(a&2?m.left+m.width:m.left,a&1?m.top+m.height:m.top);j&&(b=Eb(b,j));d&&(b.x+=(a&2?-1:1)*d.x,b.y+=(a&1?-1:1)*d.y);var o;if(h&&(o=ac(c))&&j)o.top-=j.y,o.right-=j.x,o.bottom-=j.y,o.left-=j.x;a:{j=b.n();d=0;a=(f&4&&cc(c)?f^2:f)&-5;f=ec(c);i=i?i.n():f.n();if(e||0!=a)a&2?j.x-=i.width+(e?e.right:0):e&&(j.x+=e.left),a&1?j.y-=i.height+(e?e.bottom:0):e&&(j.y+=e.top);if(h){if(o){e=
j;d=0;if(65==(h&65)&&(e.x<o.left||e.x>=o.right))h&=-2;if(132==(h&132)&&(e.y<o.top||e.y>=o.bottom))h&=-5;if(e.x<o.left&&h&1)e.x=o.left,d|=1;e.x<o.left&&e.x+i.width>o.right&&h&16&&(i.width-=e.x+i.width-o.right,d|=4);if(e.x+i.width>o.right&&h&1)e.x=Math.max(o.right-i.width,o.left),d|=1;h&2&&(d|=(e.x<o.left?16:0)|(e.x+i.width>o.right?32:0));if(e.y<o.top&&h&4)e.y=o.top,d|=2;e.y>=o.top&&e.y+i.height>o.bottom&&h&32&&(i.height-=e.y+i.height-o.bottom,d|=8);if(e.y+i.height>o.bottom&&h&4)e.y=Math.max(o.bottom-
i.height,o.top),d|=2;h&8&&(d|=(e.y<o.top?64:0)|(e.y+i.height>o.bottom?128:0));h=d}else h=256;d=h;if(d&496){c=d;break a}}e=D&&(Ea||Ma)&&F("1.9");j instanceof L?(h=j.x,j=j.y):(h=j,j=k);c.style.left=dc(h,e);c.style.top=dc(j,e);if(!(f==i||(!f||!i?0:f.width==i.width&&f.height==i.height)))e=Vb(P(Q(c))),C&&(!e||!F("8"))?(h=c.style,e?(C?(e=gc(c,Xb(c,"paddingLeft")),f=gc(c,Xb(c,"paddingRight")),j=gc(c,Xb(c,"paddingTop")),o=gc(c,Xb(c,"paddingBottom")),e=new M(j,f,o,e)):(e=R(c,"paddingLeft"),f=R(c,"paddingRight"),
j=R(c,"paddingTop"),o=R(c,"paddingBottom"),e=new M(parseFloat(j),parseFloat(f),parseFloat(o),parseFloat(e))),C?(f=ic(c,"borderLeft"),j=ic(c,"borderRight"),o=ic(c,"borderTop"),c=ic(c,"borderBottom"),c=new M(o,j,c,f)):(f=R(c,"borderLeftWidth"),j=R(c,"borderRightWidth"),o=R(c,"borderTopWidth"),c=R(c,"borderBottomWidth"),c=new M(parseFloat(o),parseFloat(j),parseFloat(c),parseFloat(f))),h.pixelWidth=i.width-c.left-e.left-e.right-c.right,h.pixelHeight=i.height-c.top-e.top-e.bottom-c.bottom):(h.pixelWidth=
i.width,h.pixelHeight=i.height)):(c=c.style,D?c.MozBoxSizing="border-box":E?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=i.width+"px",c.height=i.height+"px");c=d}return c};function vc(){}function wc(a){if("number"==typeof a){var b=new vc;b.pb=a;var c;c=a;if(0==c)c="Etc/GMT";else{var f=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);f.push(Math.floor(c/60)%100);c%=60;0!=c&&f.push(":",B(c,2));c=f.join("")}b.ac=c;0==a?a="UTC":(c=["UTC",0>a?"+":"-"],a=Math.abs(a),c.push(Math.floor(a/60)%100),a%=60,0!=a&&c.push(":",a),a=c.join(""));b.rb=[a,a];b.Ua=[];return b}b=new vc;b.ac=a.id;b.pb=-a.std_offset;b.rb=a.names;b.Ua=a.transitions;return b}
function xc(a,b){for(var c=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5,f=0;f<a.Ua.length&&c>=a.Ua[f];)f+=2;return 0==f?0:a.Ua[f-1]};function yc(a){this.d=[];"number"==typeof a?this.Ka(a):this.ua(a)}var zc=[/^\'(?:[^\']|\'\')*\'/,/^(?:G+|y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|z+|Z+)/,/^[^\'GyMkSEahKHcLQdmsvzZ]+/];yc.prototype.ua=function(a){for(;a;)for(var b=0;b<zc.length;++b){var c=a.match(zc[b]);if(c){c=c[0];a=a.substring(c.length);0==b&&("''"==c?c="'":(c=c.substring(1,c.length-1),c=c.replace(/\'\'/,"'")));this.d.push({text:c,type:b});break}}};
yc.prototype.Ka=function(a){if(4>a)a=A.N[a];else if(8>a)a=A.T[a-4];else if(12>a)a=A.N[a-8]+" "+A.T[a-8];else{this.Ka(10);return}this.ua(a)};function Ac(a,b){var c=b.getMonth();switch(a){case 5:return A.Da[c];case 4:return A.I[c];case 3:return A.qa[c];default:return B(c+1,a)}}function Bc(a,b){var c=b.getDay();switch(a){case 5:return A.Ga[c];case 4:return A.Ja[c];case 3:return A.Ia[c];default:return B(c,1)}}
function Cc(a,b){var c=b.getMonth();switch(a){case 5:return A.Fa[c];case 4:return A.Ea[c];case 3:return A.Ha[c];default:return B(c+1,a)}}
function Dc(a,b,c,f){var d=a.length;switch(a.charAt(0)){case "G":return b=0<c.getFullYear()?1:0,4<=d?A.Ca[b]:A.ma[b];case "y":return b=c.getFullYear(),0>b&&(b=-b),2==d?B(b%100,2):""+b;case "M":return Ac(d,c);case "k":return B(f.getHours()||24,d);case "S":return(f.getTime()%1E3/1E3).toFixed(Math.min(3,d)).substr(2)+(3<d?B(0,d-3):"");case "E":return b=c.getDay(),4<=d?A.sa[b]:A.Y[b];case "a":return d=f.getHours(),A.la[12<=d&&24>d?1:0];case "h":return B(f.getHours()%12||12,d);case "K":return B(f.getHours()%
12,d);case "H":return B(f.getHours(),d);case "c":return Bc(d,c);case "L":return Cc(d,c);case "Q":return b=Math.floor(c.getMonth()/3),4>d?A.ra[b]:A.pa[b];case "d":return B(c.getDate(),d);case "m":return B(f.getMinutes(),d);case "s":return B(f.getSeconds(),d);case "v":return d=k||wc(b.getTimezoneOffset()),d.ac;case "z":return a=k||wc(b.getTimezoneOffset()),4>d?a.rb[0<xc(a,b)?2:0]:a.rb[0<xc(a,b)?3:1];case "Z":return a=k||wc(b.getTimezoneOffset()),4>d?(d=-(a.pb-xc(a,b)),b=[0>d?"-":"+"],d=Math.abs(d),
b.push(B(Math.floor(d/60)%100,2),B(d%60,2))):(d=a.pb-xc(a,b),b=["GMT"],b.push(0>=d?"+":"-"),d=Math.abs(d),b.push(B(Math.floor(d/60)%100,2),":",B(d%60,2))),d=b.join("");default:return""}};function Ec(a){this.d=[];"number"==typeof a?this.Ka(a):this.ua(a)}
Ec.prototype.ua=function(a){for(var b=p,c="",f=0;f<a.length;f++){var d=a.charAt(f);if(" "==d){0<c.length&&(this.d.push({text:c,J:0,Z:p}),c="");for(this.d.push({text:" ",J:0,Z:p});f<a.length-1&&" "==a.charAt(f+1);)f++}else if(b)"'"==d?f+1<a.length&&"'"==a.charAt(f+1)?(c+="'",f++):b=p:c+=d;else if(0<=Fc.indexOf(d)){0<c.length&&(this.d.push({text:c,J:0,Z:p}),c="");var e;e=a.charAt(f);for(var h=f+1;h<a.length&&a.charAt(h)==e;)h++;e=h-f;this.d.push({text:d,J:e,Z:p});f+=e-1}else"'"==d?f+1<a.length&&"'"==
a.charAt(f+1)?(c+="'",f++):b=l:c+=d}0<c.length&&this.d.push({text:c,J:0,Z:p});a=p;for(b=0;b<this.d.length;b++)if(Gc(this.d[b])){if(!a&&b+1<this.d.length&&Gc(this.d[b+1]))a=l,this.d[b].Z=l}else a=p};Ec.prototype.Ka=function(a){11<a&&(a=10);this.ua(4>a?A.N[a]:8>a?A.T[a-4]:A.N[a-8]+" "+A.T[a-8])};var Fc="GyMdkHmsSEDahKzZvQ";function Gc(a){if(0>=a.J)return p;var b="MydhHmsSDkK".indexOf(a.text.charAt(0));return 0<b||0==b&&3>a.J}
function Hc(a,b){var c=a.substring(b[0]).match(/^\s+/);c&&(b[0]+=c[0].length)}
function Ic(a,b,c,f,d){Hc(a,b);var e=b[0],h=c.text.charAt(0),i=-1;if(Gc(c))if(0<f){if(e+f>a.length)return p;i=Jc(a.substring(0,e+f),b)}else i=Jc(a,b);switch(h){case "G":return d.Fb=Kc(a,b,A.ma),l;case "M":a:{c=i;if(0>c){c=Kc(a,b,A.I);0>c&&(c=Kc(a,b,A.qa));if(0>c){d=p;break a}d.ja=c}else d.ja=c-1;d=l}return d;case "E":return c=Kc(a,b,A.sa),0>c&&(c=Kc(a,b,A.Y)),0>c?d=p:(d.bb=c,d=l),d;case "a":return d.tb=Kc(a,b,A.la),l;case "y":a:{var j;if(0>i){j=a.charAt(b[0]);if("+"!=j&&"-"!=j){d=p;break a}b[0]++;
i=Jc(a,b);if(0>i){d=p;break a}"-"==j&&(i=-i)}!j&&2==b[0]-e&&2==c.J?(a=i,b=(new Date).getFullYear()-80,c=b%100,d.dc=a==c,a+=100*Math.floor(b/100)+(a<c?100:0),d.M=a):d.M=i;d=l}return d;case "Q":return 0>i?(c=Kc(a,b,A.pa),0>c&&(c=Kc(a,b,A.ra)),0>c?d=p:(d.ja=3*c,d.$=1,d=l)):d=p,d;case "d":return d.$=i,l;case "S":return a=b[0]-e,d.mb=3>a?i*Math.pow(10,3-a):Math.round(i/Math.pow(10,a-3)),l;case "h":12==i&&(i=0);case "K":case "H":case "k":return d.f=i,l;case "m":return d.k=i,l;case "s":return d.l=i,l;case "z":case "Z":case "v":a.indexOf("GMT",
b[0])==b[0]&&(b[0]+=3);a:if(b[0]>=a.length)d.sb=0,d=l;else{c=1;switch(a.charAt(b[0])){case "-":c=-1;case "+":b[0]++}e=b[0];i=Jc(a,b);if(0==i&&b[0]==e)d=p;else{if(b[0]<a.length&&":"==a.charAt(b[0])){j=60*i;b[0]++;e=b[0];i=Jc(a,b);if(0==i&&b[0]==e){d=p;break a}j+=i}else j=i,j=24>j&&2>=b[0]-e?60*j:j%100+60*(j/100);d.sb=-(j*c);d=l}}return d;default:return p}}function Jc(a,b){var c=a.substring(b[0]).match(/^\d+/);if(!c)return-1;b[0]+=c[0].length;return parseInt(c[0],10)}
function Kc(a,b,c){for(var f=0,d=-1,a=a.substring(b[0]).toLowerCase(),e=0;e<c.length;e++){var h=c[e].length;h>f&&0==a.indexOf(c[e].toLowerCase())&&(d=e,f=h)}0<=d&&(b[0]+=f);return d}function Lc(){};function Mc(){}(function(a){a.Gb=function(){return a.rc||(a.rc=new a)}})(Mc);Mc.prototype.tc=0;Mc.Gb();function U(a){this.c=a||P();this.Ac=Nc}z(U,jc);U.prototype.qc=Mc.Gb();var Nc=n;r=U.prototype;r.fa=n;r.p=p;r.b=n;r.Ac=n;r.sc=n;r.G=n;r.t=n;r.s=n;r.bc=p;function Oc(a){return a.fa||(a.fa=":"+(a.qc.tc++).toString(36))}r.i=aa("b");function V(a){return a.da||(a.da=new lc(a))}function Pc(a,b){a==b&&g(Error("Unable to set parent component"));b&&a.G&&a.fa&&a.G.s&&a.fa&&a.fa in a.G.s&&a.G.s[a.fa]&&a.G!=b&&g(Error("Unable to set parent component"));a.G=b;U.h.nb.call(a,b)}r.getParent=aa("G");
r.nb=function(a){this.G&&this.G!=a&&g(Error("Method not supported"));U.h.nb.call(this,a)};r.gb=aa("c");r.C=function(){this.b=this.c.createElement("div")};function Qc(a,b){a.p&&g(Error("Component already rendered"));if(b&&a.vb(b)){a.bc=l;if(!a.c||a.c.e!=Q(b))a.c=P(b);a.aa(b);a.D()}else g(Error("Invalid element to decorate"))}r.vb=function(){return l};r.aa=function(a){this.b=a};r.D=function(){this.p=l;Rc(this,function(a){!a.p&&a.i()&&a.D()})};
r.O=function(){Rc(this,function(a){a.p&&a.O()});this.da&&oc(this.da);this.p=p};r.j=function(){U.h.j.call(this);this.p&&this.O();this.da&&(this.da.u(),delete this.da);Rc(this,function(a){a.u()});!this.bc&&this.b&&Qb(this.b);this.G=this.sc=this.b=this.s=this.t=n};function Rc(a,b){a.t&&gb(a.t,b,k)}
r.removeChild=function(a,b){if(a){var c=u(a)?a:Oc(a),a=this.s&&c?(c in this.s?this.s[c]:k)||n:n;if(c&&a){var f=this.s;c in f&&delete f[c];hb(this.t,a);b&&(a.O(),a.b&&Qb(a.b));Pc(a,n)}}a||g(Error("Child is not in parent component"));return a};function Sc(a,b){switch(b){case 1:return 0==a%4&&(0!=a%100||0==a%400)?29:28;case 5:case 8:case 10:case 3:return 30}return 31}function W(a,b,c,f,d,e){u(a)?(this.r=a==Tc?b:0,this.q=a==Uc?b:0,this.o=a==Vc?b:0,this.f=a==Wc?b:0,this.k=a==Xc?b:0,this.l=a==Yc?b:0):(this.r=a||0,this.q=b||0,this.o=c||0,this.f=f||0,this.k=d||0,this.l=e||0)}
W.prototype.Ba=function(a){var b=Math.min(this.r,this.q,this.o,this.f,this.k,this.l),c=Math.max(this.r,this.q,this.o,this.f,this.k,this.l);if(0>b&&0<c)return n;if(!a&&0==b&&0==c)return"PT0S";c=[];0>b&&c.push("-");c.push("P");(this.r||a)&&c.push(Math.abs(this.r)+"Y");(this.q||a)&&c.push(Math.abs(this.q)+"M");(this.o||a)&&c.push(Math.abs(this.o)+"D");if(this.f||this.k||this.l||a)c.push("T"),(this.f||a)&&c.push(Math.abs(this.f)+"H"),(this.k||a)&&c.push(Math.abs(this.k)+"M"),(this.l||a)&&c.push(Math.abs(this.l)+
"S");return c.join("")};W.prototype.fb=function(a){return a.r==this.r&&a.q==this.q&&a.o==this.o&&a.f==this.f&&a.k==this.k&&a.l==this.l};W.prototype.n=function(){return new W(this.r,this.q,this.o,this.f,this.k,this.l)};var Tc="y",Uc="m",Vc="d",Wc="h",Xc="n",Yc="s";W.prototype.add=function(a){this.r+=a.r;this.q+=a.q;this.o+=a.o;this.f+=a.f;this.k+=a.k;this.l+=a.l};
function X(a,b,c){"number"==typeof a?(this.a=new Date(a,b||0,c||1),Zc(this,c||1)):fa(a)?(this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate()),Zc(this,a.getDate())):(this.a=new Date,this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0))}r=X.prototype;r.K=A.na;r.ca=A.oa;r.n=function(){var a=new X(this.a);a.K=this.K;a.ca=this.ca;return a};r.getFullYear=function(){return this.a.getFullYear()};r.getYear=function(){return this.getFullYear()};r.getMonth=function(){return this.a.getMonth()};
r.getDate=function(){return this.a.getDate()};r.getTime=function(){return this.a.getTime()};r.getDay=function(){return this.a.getDay()};r.getUTCFullYear=function(){return this.a.getUTCFullYear()};r.getUTCMonth=function(){return this.a.getUTCMonth()};r.getUTCDate=function(){return this.a.getUTCDate()};r.getUTCHours=function(){return this.a.getUTCHours()};r.getUTCMinutes=function(){return this.a.getUTCMinutes()};r.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};
function $c(a){a=a.getTimezoneOffset();if(0==a)a="Z";else var b=Math.abs(a)/60,c=Math.floor(b),b=60*(b-c),a=(0<a?"-":"+")+B(c,2)+":"+B(b,2);return a}r.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};r.setFullYear=function(a){this.a.setFullYear(a)};r.setMonth=function(a){this.a.setMonth(a)};r.setDate=function(a){this.a.setDate(a)};r.setTime=function(a){this.a.setTime(a)};
r.add=function(a){if(a.r||a.q){var b=this.getMonth()+a.q+12*a.r,c=this.getYear()+Math.floor(b/12),b=b%12;0>b&&(b+=12);var f=Math.min(Sc(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(f)}a.o&&(b=new Date(this.getYear(),this.getMonth(),this.getDate(),12),a=new Date(b.getTime()+864E5*a.o),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),this.setDate(a.getDate()),Zc(this,a.getDate()))};
r.Ba=function(a,b){return[this.getFullYear(),B(this.getMonth()+1,2),B(this.getDate(),2)].join(a?"-":"")+(b?$c(this):"")};r.fb=function(a){return this.getYear()==a.getYear()&&this.getMonth()==a.getMonth()&&this.getDate()==a.getDate()};r.toString=function(){return this.Ba()};function Zc(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}r.valueOf=function(){return this.a.valueOf()};
function ad(a,b,c,f,d,e,h){this.a="number"==typeof a?new Date(a,b||0,c||1,f||0,d||0,e||0,h||0):new Date(a?a.getTime():na())}z(ad,X);r=ad.prototype;r.getHours=function(){return this.a.getHours()};r.getMinutes=function(){return this.a.getMinutes()};r.getSeconds=function(){return this.a.getSeconds()};r.getUTCHours=function(){return this.a.getUTCHours()};r.getUTCMinutes=function(){return this.a.getUTCMinutes()};r.setHours=function(a){this.a.setHours(a)};r.setMinutes=function(a){this.a.setMinutes(a)};
r.setSeconds=function(a){this.a.setSeconds(a)};r.setMilliseconds=function(a){this.a.setMilliseconds(a)};r.setUTCHours=function(a){this.a.setUTCHours(a)};r.add=function(a){X.prototype.add.call(this,a);a.f&&this.setHours(this.a.getHours()+a.f);a.k&&this.setMinutes(this.a.getMinutes()+a.k);a.l&&this.setSeconds(this.a.getSeconds()+a.l)};
r.Ba=function(a,b){var c=X.prototype.Ba.call(this,a);return a?c+" "+B(this.getHours(),2)+":"+B(this.getMinutes(),2)+":"+B(this.getSeconds(),2)+(b?$c(this):""):c+"T"+B(this.getHours(),2)+B(this.getMinutes(),2)+B(this.getSeconds(),2)+(b?$c(this):"")};r.fb=function(a){return this.getTime()==a.getTime()};r.toString=function(){return this.Ba()};r.n=function(){var a=new ad(this.a);a.K=this.K;a.ca=this.ca;return a};function bd(a,b){a&&this.Za(a,b)}z(bd,jc);r=bd.prototype;r.b=n;r.Na=n;r.ib=n;r.Oa=n;r.R=-1;r.Q=-1;
var cd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},dd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},ed={61:187,59:186},fd=C||E&&F("525");r=bd.prototype;
r.lc=function(a){if(E&&(17==this.R&&!a.ctrlKey||18==this.R&&!a.altKey))this.Q=this.R=-1;fd&&!pc(a.keyCode,this.R,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.Q=D&&a.keyCode in ed?ed[a.keyCode]:a.keyCode};r.mc=function(){this.Q=this.R=-1};
r.handleEvent=function(a){var b=a.F,c,f;C&&"keypress"==a.type?(c=this.Q,f=13!=c&&27!=c?b.keyCode:0):E&&"keypress"==a.type?(c=this.Q,f=0<=b.charCode&&63232>b.charCode&&qc(c)?b.charCode:0):Ja?(c=this.Q,f=qc(c)?b.keyCode:0):(c=b.keyCode||this.Q,f=b.charCode||0,Ea&&63==f&&!c&&(c=191));var d=c,e=b.keyIdentifier;c?63232<=c&&c in cd?d=cd[c]:25==c&&a.shiftKey&&(d=9):e&&e in dd&&(d=dd[e]);a=d==this.R;this.R=d;b=new gd(d,f,a,b);try{this.dispatchEvent(b)}finally{b.u()}};r.i=aa("b");
r.Za=function(a,b){this.Oa&&this.detach();this.b=a;this.Na=tb(this.b,"keypress",this,b);this.ib=tb(this.b,"keydown",this.lc,b,this);this.Oa=tb(this.b,"keyup",this.mc,b,this)};r.detach=function(){if(this.Na)K(this.Na),K(this.ib),K(this.Oa),this.Oa=this.ib=this.Na=n;this.b=n;this.Q=this.R=-1};r.j=function(){bd.h.j.call(this);this.detach()};function gd(a,b,c,f){f&&this.xa(f,k);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}z(gd,qb);function hd(a,b){a.setAttribute("role",b);a.Jc=b};function Y(a,b,c){U.call(this,c);this.H=b||A;this.Gc=this.H.Y;this.a=new X(a);this.a.ca=this.H.oa;this.a.K=this.H.na;this.m=this.a.n();this.m.setDate(1);this.Va=",,,,,,".split(",");this.Va[this.H.ta[0]]=Z()+"-wkend-start";this.Va[this.H.ta[1]]=Z()+"-wkend-end";this.ga={}}z(Y,U);r=Y.prototype;r.Wb=l;r.Dc=l;r.hc=l;r.ob=l;r.Zb=l;r.Ya=l;r.Yb=l;r.Fc=p;r.Bb=n;r.La=n;r.cb=n;var id=0;function Z(){return"goog-date-picker"}r=Y.prototype;r.Sb=function(){this.m.add(new W(Uc,-1));jd(this)};
r.Nb=function(){this.m.add(new W(Uc,1));jd(this)};r.zc=function(){this.m.add(new W(Tc,-1));jd(this)};r.uc=function(){this.m.add(new W(Tc,1));jd(this)};r.Vb=function(){this.setDate(new X)};r.Ub=function(){this.Ya&&this.setDate(n)};r.getDate=function(){return this.a&&this.a.n()};
r.setDate=function(a){var b=a!=this.a&&!(a&&this.a&&a.getFullYear()==this.a.getFullYear()&&a.getMonth()==this.a.getMonth()&&a.getDate()==this.a.getDate());this.a=a&&new X(a);a&&(this.m.set(this.a),this.m.setDate(1));jd(this);this.dispatchEvent(new kd("select",this,this.a));b&&this.dispatchEvent(new kd("change",this,this.a))};
r.aa=function(a){Y.h.aa.call(this,a);a.className=Z();var b=this.c.createElement("table"),c=this.c.createElement("thead"),f=this.c.createElement("tbody"),d=this.c.createElement("tfoot");hd(f,"grid");f.tabIndex="0";this.qb=f;this.$b=d;var e=this.c.createElement("tr");e.className=Z()+"-head";if(this.La=e){for(var h=this.La;h.firstChild;)h.removeChild(h.firstChild);var i,j;if(this.Fc)i=this.c.createElement("td"),i.colSpan=this.ob?1:2,$(this,i,"\u00ab",this.Sb),h.appendChild(i),i=this.c.createElement("td"),
i.colSpan=this.ob?6:5,i.className=Z()+"-monthyear",h.appendChild(i),this.eb=i,i=this.c.createElement("td"),$(this,i,"\u00bb",this.Nb),h.appendChild(i);else{var m=this.H.N[0].toLowerCase();i=this.c.createElement("td");i.colSpan=5;$(this,i,"\u00ab",this.Sb);this.U=$(this,i,"",this.Cc,Z()+"-month");$(this,i,"\u00bb",this.Nb);j=this.c.createElement("td");j.colSpan=3;$(this,j,"\u00ab",this.zc);this.va=$(this,j,"",this.Ec,Z()+"-year");$(this,j,"\u00bb",this.uc);m.indexOf("y")<m.indexOf("m")?(h.appendChild(j),
h.appendChild(i)):(h.appendChild(i),h.appendChild(j))}}c.appendChild(e);this.B=[];for(i=0;7>i;i++){e=this.c.createElement("tr");this.B[i]=[];for(j=0;8>j;j++){h=this.c.createElement(0==j||0==i?"th":"td");if((0==j||0==i)&&j!=i)h.className=0==j?Z()+"-week":Z()+"-wday",hd(h,0==j?"rowheader":"columnheader");e.appendChild(h);this.B[i][j]=h}f.appendChild(e)}e=this.c.createElement("tr");e.className=Z()+"-foot";h=this.cb=e;Pb(h);i=this.c.createElement("td");i.colSpan=2;i.className=Z()+"-today-cont";this.Eb=
$(this,i,"Today",this.Vb);h.appendChild(i);i=this.c.createElement("td");i.colSpan=4;h.appendChild(i);i=this.c.createElement("td");i.colSpan=2;i.className=Z()+"-none-cont";this.Db=$(this,i,"None",this.Ub);h.appendChild(i);S(this.Eb,this.Yb);S(this.Db,this.Ya);S(this.$b,this.Yb||this.Ya);d.appendChild(e);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(f);b.appendChild(d);a.appendChild(b);if(this.i()){if(this.Zb)for(b=0;7>b;b++)Tb(this.B[0][b+1],this.Gc[((b+this.m.K+7)%7+1)%7]);S(this.B[0][0].parentNode,
this.Zb)}jd(this);a.tabIndex=0};r.C=function(){Y.h.C.call(this);this.aa(this.i())};r.D=function(){Y.h.D.call(this);var a=V(this);T(a,this.qb,"click",this.jc);T(a,ld(this,this.i()),"key",this.kc)};r.O=function(){Y.h.O.call(this);this.ba();for(var a in this.ga)this.ga[a].u();this.ga={}};r.j=function(){Y.h.j.call(this);this.Db=this.Eb=this.va=this.eb=this.U=this.cb=this.La=this.$b=this.qb=this.B=n};
r.jc=function(a){if("TD"==a.target.tagName){var b,c=-2,f=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,f++);this.setDate(this.ea[f][c].n())}};
r.kc=function(a){var b,c;switch(a.keyCode){case 33:a.preventDefault();b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault(),this.Vb();case 46:a.preventDefault(),this.Ub();default:return}this.a?(a=this.a.n(),a.add(new W(0,b,c))):(a=this.m.n(),a.setDate(1));this.setDate(a)};
r.Cc=function(a){a.stopPropagation();for(var a=[],b=0;12>b;b++)a.push(this.H.I[b]);md(this,this.U,a,this.nc,this.H.I[this.m.getMonth()])};r.Ec=function(a){a.stopPropagation();for(var a=[],b=this.m.getFullYear()-5,c=0;11>c;c++)a.push(""+(b+c));md(this,this.va,a,this.oc,""+this.m.getFullYear())};r.nc=function(a){for(var b=-1;a;a=a.previousElementSibling!=k?a.previousElementSibling:Rb(a.previousSibling),b++);this.m.setMonth(b);jd(this);this.U.focus&&this.U.focus()};
r.oc=function(a){3==a.firstChild.nodeType&&(this.m.setFullYear(Number(a.firstChild.nodeValue)),jd(this));this.va.focus()};
function md(a,b,c,f,d){a.ba();var e=a.c.createElement("div");e.className=Z()+"-menu";a.ia=n;for(var h=a.c.createElement("ul"),i=0;i<c.length;i++){var j=a.c.C("li",n,c[i]);if(c[i]==d)a.ia=j;h.appendChild(j)}e.appendChild(h);e.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";e.style.top=b.offsetTop+"px";e.style.width=b.clientWidth+"px";a.U.parentNode.appendChild(e);a.V=e;if(!a.ia)a.ia=h.firstChild;a.ia.className=Z()+"-menu-selected";a.lb=f;b=V(a);T(b,a.V,"click",a.Hb);T(b,ld(a,a.V),"key",a.Ib);
T(b,a.c.e,"click",a.ba);e.tabIndex=0;e.focus()}r.Hb=function(a){a.stopPropagation();this.ba();this.lb&&this.lb(a.target)};
r.Ib=function(a){a.stopPropagation();var b,c=this.ia;switch(a.keyCode){case 35:a.preventDefault();b=c.parentNode.lastChild;break;case 36:a.preventDefault();b=c.parentNode.firstChild;break;case 38:a.preventDefault();b=c.previousSibling;break;case 40:a.preventDefault();b=c.nextSibling;break;case 13:case 9:case 0:a.preventDefault(),this.ba(),this.lb(c)}if(b&&b!=c)c.className="",b.className=Z()+"-menu-selected",this.ia=b};
r.ba=function(){if(this.V){var a=V(this);nc(a,this.V,"click",this.Hb);nc(a,ld(this,this.V),"key",this.Ib);nc(a,this.c.e,"click",this.ba);Qb(this.V);delete this.V}};function $(a,b,c,f,d){var e=[Z()+"-btn"];d&&e.push(d);d=a.c.createElement("button");d.className=e.join(" ");d.appendChild(a.c.createTextNode(c));b.appendChild(d);T(V(a),d,"click",function(a){a.preventDefault();f.call(this,a)});return d}
function jd(a){if(a.i()){var b=a.m.n();b.setDate(1);a.eb&&Tb(a.eb,a.H.I[b.getMonth()]+(" "+b.getFullYear()));a.U&&Tb(a.U,a.H.I[b.getMonth()]);a.va&&Tb(a.va,""+b.getFullYear());var c=((b.getDay()+6)%7-b.K+7)%7,f=Sc(b.getFullYear(),b.getMonth());b.add(new W(Uc,-1));b.setDate(Sc(b.getFullYear(),b.getMonth())-(c-1));a.Wb&&!a.hc&&33>f+c&&b.add(new W(Vc,-7));c=new W(Vc,1);a.ea=[];for(f=0;6>f;f++){a.ea[f]=[];for(var d=0;7>d;d++)a.ea[f][d]=b.n(),b.add(c)}if(a.i())for(var b=a.m.getMonth(),d=new X,c=d.getFullYear(),
f=d.getMonth(),d=d.getDate(),e=0;6>e;e++){if(a.ob){var h=a.B[e+1][0],i;i=a.ea[e][0];var j=i.getDate(),j=new Date(i.getFullYear(),i.getMonth(),j),m=i.K||0;i=j.valueOf()+864E5*(((i.ca||3)-m+7)%7-((j.getDay()+6)%7-m+7)%7);i=Math.floor(Math.round((i-(new Date((new Date(i)).getFullYear(),0,1)).valueOf())/864E5)/7)+1;Tb(h,i);a.B[e+1][0].className=Z()+"-week"}else Tb(a.B[e+1][0],""),a.B[e+1][0].className="";for(h=0;7>h;h++){i=a.ea[e][h];j=a.B[e+1][h+1];if(!j.id)j.id="goog-dp-"+id++;hd(j,"gridcell");m=[Z()+
"-date"];if(a.Dc||i.getMonth()==b){i.getMonth()!=b&&m.push(Z()+"-other-month");var q=(h+a.m.K+7)%7;a.Va[q]&&m.push(a.Va[q]);i.getDate()==d&&i.getMonth()==f&&i.getFullYear()==c&&m.push(Z()+"-today");a.a&&i.getDate()==a.a.getDate()&&i.getMonth()==a.a.getMonth()&&i.getFullYear()==a.a.getFullYear()&&(m.push(Z()+"-selected"),a.qb.setAttribute("aria-activedescendant",j.id));a.Bb&&(q=a.Bb(i))&&m.push(q);Tb(j,i.getDate())}else Tb(j,"");j.className=m.join(" ")}4<=e&&S(a.B[e+1][0].parentNode,a.ea[e][0].getMonth()==
b||a.Wb)}}}function ld(a,b){var c=ga(b);c in a.ga||(a.ga[c]=new bd(b));return a.ga[c]}function kd(a,b,c){H.call(this,a,b);this.yb=c}z(kd,H);function nd(){}nd.prototype.L=function(){};function od(a,b){this.element=a;this.ab=b}z(od,nd);od.prototype.L=function(a,b,c){uc(this.element,this.ab,a,b,k,c)};function pd(a,b,c){od.call(this,a,b);this.cc=c}z(pd,od);pd.prototype.L=function(a,b,c,f){var d=uc(this.element,this.ab,a,b,n,c,10,f);if(d&496){var e=qd(d,this.ab),b=qd(d,b),d=uc(this.element,e,a,b,n,c,10,f);d&496&&(e=qd(d,e),b=qd(d,b),this.cc?uc(this.element,e,a,b,n,c,5,f):uc(this.element,e,a,b,n,c,0,f))}};function qd(a,b){a&48&&(b^=2);a&192&&(b^=1);return b};function rd(a,b){this.yc=4;this.Ta=b||k;rc.call(this,a)}z(rd,rc);rd.prototype.L=function(){if(this.Ta){var a=!this.P&&"move_offscreen"!=this.ka,b=this.i();if(a)b.style.visibility="hidden",S(b,l);this.Ta.L(b,this.yc,this.Ic);a&&S(b,p)}};function sd(a,b){U.call(this,b);this.A=a||new Y}z(sd,U);r=sd.prototype;r.A=n;r.S=n;r.Qa=n;r.Xa=l;r.C=function(){sd.h.C.call(this);this.i().className="goog-popupdatepicker";this.S=new rd(this.i())};r.D=function(){sd.h.D.call(this);if(!this.A.p){var a=this.i();a.style.visibility="hidden";S(a,p);Qc(this.A,a)}T(V(this),this.A,"change",this.ya)};r.j=function(){sd.h.j.call(this);if(this.S)this.S.u(),this.S=n;this.A.u();this.Qa=this.A=n};r.vb=function(){return p};r.getDate=function(){return this.A.getDate()};
r.setDate=function(a){this.A.setDate(a)};r.Za=function(a){T(V(this),a,"mousedown",this.Xb)};r.detach=function(a){nc(V(this),a,"mousedown",this.Xb)};r.Xb=function(a){this.Qa=a=a.currentTarget;var b=this.S;b.Ta=new od(a,5)||k;b.P&&b.L();nc(V(this),this.A,"change",this.ya);this.A.setDate(n);this.dispatchEvent("show");T(V(this),this.A,"change",this.ya);sc(this.S,l);this.Xa&&this.i().focus()};r.hb=function(){sc(this.S,p);this.Xa&&this.Qa&&this.Qa.focus()};r.ya=function(a){this.hb();this.dispatchEvent(a)};function td(a,b,c,f){U.call(this,f);this.zb=a;this.Ab=b;a=this.g=new sd(c,f);b=this.t?this.t.length:0;a.p&&!this.p&&g(Error("Component already rendered"));(0>b||b>(this.t?this.t.length:0))&&g(Error("Child component index out of bounds"));if(!this.s||!this.t)this.s={},this.t=[];a.getParent()==this?(this.s[Oc(a)]=a,hb(this.t,a)):(c=this.s,f=Oc(a),f in c&&g(Error('The object already contains the key "'+f+'"')),c[f]=a);Pc(a,this);kb(this.t,b,0,a);a.p&&this.p&&a.getParent()==this?(c=this.b,c.insertBefore(a.i(),
c.childNodes[b]||n)):this.p&&!a.p&&a.b&&a.D();this.g.Xa=p}z(td,U);r=td.prototype;r.zb=n;r.Ab=n;r.g=n;r.Rb=n;r.getDate=function(){var a=ud(this),b=this.g.getDate();a&&b?a.fb(b)||this.g.setDate(a):this.g.setDate(n);return a};r.setDate=function(a){this.g.setDate(a)};
function ud(a){var b;b=a.i();b=b.jb?b.jb.Hc():b.value;var c=ra(b);if(c){b=new ad;a:{for(var f=a.Ab,d=new Lc,a=[0],e=-1,h=0,i=0,j=0;j<f.d.length;j++)if(0<f.d[j].J)if(0>e&&f.d[j].Z&&(e=j,i=h=0),0<=e){var m=f.d[j].J;if(j==e&&(m-=i,i++,0==m)){a=0;break a}Ic(c,a,f.d[j],m,d)||(j=e-1,a[0]=h)}else{if(e=-1,!Ic(c,a,f.d[j],0,d)){a=0;break a}}else{e=-1;if(" "==f.d[j].text.charAt(0)){if(m=a[0],Hc(c,a),a[0]>m)continue}else if(c.indexOf(f.d[j].text,a[0])==a[0]){a[0]+=f.d[j].text.length;continue}a=0;break a}b:{if(d.Fb!=
k&&d.M!=k&&0==d.Fb&&0<d.M)d.M=-(d.M-1);d.M!=k&&b.setFullYear(d.M);c=b.getDate();b.setDate(1);d.ja!=k&&b.setMonth(d.ja);d.$!=k?b.setDate(d.$):b.setDate(c);if(v(b.setHours)){if(d.f==k)d.f=b.getHours();d.tb!=k&&0<d.tb&&12>d.f&&(d.f+=12);b.setHours(d.f)}v(b.setMinutes)&&d.k!=k&&b.setMinutes(d.k);v(b.setSeconds)&&d.l!=k&&b.setSeconds(d.l);v(b.setMilliseconds)&&d.mb!=k&&b.setMilliseconds(d.mb);if(d.M!=k&&d.M!=b.getFullYear()||d.ja!=k&&d.ja!=b.getMonth()||d.$!=k&&d.$!=b.getDate()||24<=d.f||60<=d.k||60<=
d.l||1E3<=d.mb)d=p;else{d.sb!=k&&b.setTime(b.getTime()+6E4*(d.sb-b.getTimezoneOffset()));d.dc&&(c=new Date,c.setFullYear(c.getFullYear()-80),b.getTime()<c.getTime()&&b.setFullYear(c.getFullYear()+100));if(d.bb!=k)if(d.$==k)d=(7+d.bb-b.getDay())%7,3<d&&(d-=7),c=b.getMonth(),b.setDate(b.getDate()+d),b.getMonth()!=c&&b.setDate(b.getDate()+(0<d?-7:7));else if(d.bb!=b.getDay()){d=p;break b}d=l}}a=d?a[0]-0:0}if(0<a)return b}return n}r.C=function(){this.b=this.gb().C("input",{type:"text"});this.g.C()};
r.D=function(){td.h.D.call(this);var a=this.i();(this.Rb||Ub(this.gb()).body).appendChild(this.g.i());this.g.D();this.g.Za(a);this.g.setDate(ud(this));a=V(this);T(a,this.g,"change",this.ya);T(a,this.g,"show",this.wc)};r.O=function(){td.h.O.call(this);this.g.detach(this.i());this.g.O();Qb(this.g.i())};r.aa=function(a){td.h.aa.call(this,a);this.g.C()};r.j=function(){td.h.j.call(this);this.g.u();this.Rb=this.g=n};r.hb=function(){this.g.hb()};r.wc=function(){this.setDate(ud(this))};
r.ya=function(a){var b;if(a.yb){b=this.zb;for(var a=a.yb,c=[],f=0;f<b.d.length;++f){var d=b.d[f].text;1==b.d[f].type?c.push(Dc(d,a,a,a)):c.push(d)}b=c.join("")}else b="";a=this.i();a.jb?a.jb.Kc(b):a.value=b};function vd(a,b,c){var f=new yc("yyyy'-'MM'-'dd"),d=new Ec("yyyy'-'MM'-'dd"),e=A;"ja"===b?e=oa:"zh"===b?e=pa:"zh-tw"===b&&(e=qa);var b=new Y(n,e),h=new td(f,d,b);c&&tb(h,"show",function(){var b=h.g.S;b.Ta=new pd(a,5,l)||k;b.P&&b.L()});Qc(h,a)}var wd="grn.closure_proxy.addDatePicker".split("."),xd=t;!(wd[0]in xd)&&xd.execScript&&xd.execScript("var "+wd[0]);for(var yd;wd.length&&(yd=wd.shift());)!wd.length&&vd!==k?xd[yd]=vd:xd=xd[yd]?xd[yd]:xd[yd]={};})();
