<?xml version="1.0" encoding="{$encoding}"?>
<methodResponse>
  <params>
    <param>
      <value>
        <struct>
          <member>
            <name>apiver</name>
            <value><double>{$api_ver}</double></value>
          </member>
          <member>
            <name>sig</name>
            <value><string>{$sig}</string></value>
          </member>
        </struct>
      </value>
    </param>
  </params>
</methodResponse>
