(function(){var h=void 0,i=!0,j=null,k=!1,t,aa=aa||{},u=this;function ba(a,b){var c=a.split("."),d=u;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==h?d[f]=b:d=d[f]?d[f]:d[f]={}}function ga(a){for(var a=a.split("."),b=u,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}function ha(){}
function v(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ia(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){return"string"==typeof a}function z(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ka=0;function la(a,b,c){return a.call.apply(a.bind,arguments)}
function ma(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return A.apply(j,arguments)}var na=Date.now||function(){return+new Date};
function B(a,b){function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a};function oa(a){this.stack=Error().stack||"";if(a)this.message=""+a}B(oa,Error);oa.prototype.name="CustomError";function pa(a,b){for(var c=1;c<arguments.length;c++)var d=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function qa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ra(a){if(!sa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ta,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ua,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(va,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(wa,"&quot;"));return a}var ta=/&/g,ua=/</g,va=/>/g,wa=/\"/g,sa=/[&<>\"]/;function xa(a,b){b.unshift(a);oa.call(this,pa.apply(j,b));b.shift();this.Ta=a}B(xa,oa);xa.prototype.name="AssertionError";function Aa(a,b){throw new xa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var D=Array.prototype,Ba=D.indexOf?function(a,b,c){return D.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(w(a))return!w(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},E=D.forEach?function(a,b,c){D.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function Ca(a,b,c){return 2>=arguments.length?D.slice.call(a,b):D.slice.call(a,b,c)};var Da;function Ea(a){return(a=a.className)&&"function"==typeof a.split?a.split(/\s+/):[]}function Fa(a,b){for(var c=Ea(a),d=Ca(arguments,1),f=c,e=0,g=0;g<d.length;g++)0<=Ba(f,d[g])||(f.push(d[g]),e++);a.className=c.join(" ")};function Ga(a){var b=F,c;for(c in b)a.call(h,b[c],c,b)}function Ha(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ia(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Ja="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function Ka(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ja.length;e++)c=Ja[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var G,La,Ma,Na;function Oa(){return u.navigator?u.navigator.userAgent:j}Na=Ma=La=G=k;var Pa;if(Pa=Oa()){var Qa=u.navigator;G=0==Pa.indexOf("Opera");La=!G&&-1!=Pa.indexOf("MSIE");Ma=!G&&-1!=Pa.indexOf("WebKit");Na=!G&&!Ma&&"Gecko"==Qa.product}var Ta=G,H=La,Ua=Na,Va=Ma,Wa=u.navigator,Xa=-1!=(Wa&&Wa.platform||"").indexOf("Mac"),Ya;
a:{var Za="",I;if(Ta&&u.opera)var $a=u.opera.version,Za="function"==typeof $a?$a():$a;else if(Ua?I=/rv\:([^\);]+)(\)|;)/:H?I=/MSIE\s+([^\);]+)(\)|;)/:Va&&(I=/WebKit\/(\S+)/),I)var ab=I.exec(Oa()),Za=ab?ab[1]:"";if(H){var bb,cb=u.document;bb=cb?cb.documentMode:h;if(bb>parseFloat(Za)){Ya=""+bb;break a}}Ya=Za}var db={};
function eb(a){var b;if(!(b=db[a])){b=0;for(var c=qa(""+Ya).split("."),d=qa(""+a).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",n=d[e]||"",q=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=q.exec(g)||["","",""],m=l.exec(n)||["","",""];if(0==r[0].length&&0==m[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==r[2].length)<(0==
m[2].length)?-1:(0==r[2].length)>(0==m[2].length)?1:0)||(r[2]<m[2]?-1:r[2]>m[2]?1:0)}while(0==b)}b=db[a]=0<=b}return b}var fb={};function gb(){return fb[9]||(fb[9]=H&&document.documentMode&&9<=document.documentMode)};!H||gb();!Ua&&!H||H&&gb()||Ua&&eb("1.9.1");H&&eb("9");function J(a){this.O=a||u.document||document}J.prototype.createElement=function(a){return this.O.createElement(a)};J.prototype.createTextNode=function(a){return this.O.createTextNode(a)};J.prototype.appendChild=function(a,b){a.appendChild(b)};function hb(a){a=""+a;if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var ib=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function jb(){}var kb=0;t=jb.prototype;t.key=0;t.p=k;t.$=k;t.C=function(a,b,c,d,f,e){if("function"==v(a))this.ma=i;else if(a&&a.handleEvent&&"function"==v(a.handleEvent))this.ma=k;else throw Error("Invalid listener argument");this.u=a;this.ra=b;this.src=c;this.type=d;this.capture=!!f;this.T=e;this.$=k;this.key=++kb;this.p=k};t.handleEvent=function(a){return this.ma?this.u.call(this.T||this.src,a):this.u.handleEvent.call(this.u,a)};!H||gb();var lb=!H||gb();H&&eb("8");function K(){}K.prototype.ea=k;K.prototype.z=function(){if(!this.ea)this.ea=i,this.i()};K.prototype.i=function(){this.Aa&&mb.apply(j,this.Aa)};function mb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ia(d)?mb.apply(j,d):d&&"function"==typeof d.z&&d.z()}};function L(a,b){this.type=a;this.currentTarget=this.target=b}B(L,K);L.prototype.i=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.n=k;L.prototype.I=i;function nb(a){nb[" "](a);return a}nb[" "]=ha;function M(a,b){a&&this.C(a,b)}B(M,L);t=M.prototype;t.target=j;t.relatedTarget=j;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=k;t.altKey=k;t.shiftKey=k;t.metaKey=k;t.Ia=k;t.ha=j;
t.C=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(Ua){var f;a:{try{nb(d.nodeName);f=i;break a}catch(e){}f=k}f||(d=j)}}else if("mouseover"==c)d=a.fromElement;else if("mouseout"==c)d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Ia=Xa?a.metaKey:a.ctrlKey;this.state=a.state;this.ha=a;delete this.I;delete this.n};t.i=function(){M.Y.i.call(this);this.relatedTarget=this.currentTarget=this.target=this.ha=j};var Q={},R={},F={},S={};
function ob(a,b,c,d,f){if(b)if("array"==v(b))for(var e=0;e<b.length;e++)ob(a,b[e],c,d,f);else{var d=!!d,g=R;b in g||(g[b]={b:0,f:0});g=g[b];d in g||(g[d]={b:0,f:0},g.b++);var g=g[d],n=z(a),q;g.f++;if(g[n]){q=g[n];for(e=0;e<q.length;e++)if(g=q[e],g.u==c&&g.T==f){if(g.p)break;return}}else q=g[n]=[],g.b++;e=pb();e.src=a;g=new jb;g.C(c,e,a,b,d,f);c=g.key;e.key=c;q.push(g);Q[c]=g;F[n]||(F[n]=[]);F[n].push(g);a.addEventListener?(a==u||!a.da)&&a.addEventListener(b,e,d):a.attachEvent(b in S?S[b]:S[b]="on"+
b,e)}else throw Error("Invalid event type");}function pb(){var a=qb,b=lb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function rb(a,b,c,d,f){if("array"==v(b))for(var e=0;e<b.length;e++)rb(a,b[e],c,d,f);else{d=!!d;a:{e=R;if(b in e&&(e=e[b],d in e&&(e=e[d],a=z(a),e[a]))){a=e[a];break a}a=j}if(a)for(e=0;e<a.length;e++)if(a[e].u==c&&a[e].capture==d&&a[e].T==f){sb(a[e].key);break}}}
function sb(a){if(Q[a]){var b=Q[a];if(!b.p){var c=b.src,d=b.type,f=b.ra,e=b.capture;c.removeEventListener?(c==u||!c.da)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in S?S[d]:S[d]="on"+d,f);c=z(c);f=R[d][e][c];if(F[c]){var g=F[c],n=Ba(g,b);0<=n&&D.splice.call(g,n,1);0==g.length&&delete F[c]}b.p=i;f.pa=i;tb(d,e,c,f);delete Q[a]}}}
function tb(a,b,c,d){if(!d.D&&d.pa){for(var f=0,e=0;f<d.length;f++)d[f].p?d[f].ra.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.pa=k;0==e&&(delete R[a][b][c],R[a][b].b--,0==R[a][b].b&&(delete R[a][b],R[a].b--),0==R[a].b&&delete R[a])}}function ub(a){var b,c=0,d=b==j;b=!!b;if(a==j)Ga(function(a){for(var e=a.length-1;0<=e;e--){var f=a[e];if(d||b==f.capture)sb(f.key),c++}});else if(a=z(a),F[a])for(var a=F[a],f=a.length-1;0<=f;f--){var e=a[f];if(d||b==e.capture)sb(e.key),c++}}
function T(a,b,c,d,f){var e=1,b=z(b);if(a[b]){a.f--;a=a[b];a.D?a.D++:a.D=1;try{for(var g=a.length,n=0;n<g;n++){var q=a[n];q&&!q.p&&(e&=vb(q,f)!==k)}}finally{a.D--,tb(c,d,b,a)}}return Boolean(e)}function vb(a,b){var c=a.handleEvent(b);a.$&&sb(a.key);return c}
function qb(a,b){if(!Q[a])return i;var c=Q[a],d=c.type,f=R;if(!(d in f))return i;var f=f[d],e,g;if(!lb){e=b||ga("window.event");var n=i in f,q=k in f;if(n){if(0>e.keyCode||e.returnValue!=h)return i;a:{var l=k;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(r){l=i}if(l||e.returnValue==h)e.returnValue=i}}l=new M;l.C(e,this);e=i;try{if(n){for(var m=[],x=l.currentTarget;x;x=x.parentNode)m.push(x);g=f[i];g.f=g.b;for(var o=m.length-1;!l.n&&0<=o&&g.f;o--)l.currentTarget=m[o],e&=T(g,m[o],d,i,l);if(q){g=f[k];
g.f=g.b;for(o=0;!l.n&&o<m.length&&g.f;o++)l.currentTarget=m[o],e&=T(g,m[o],d,k,l)}}else e=vb(c,l)}finally{if(m)m.length=0;l.z()}return e}d=new M(b,this);try{e=vb(c,d)}finally{d.z()}return e};function wb(){}B(wb,K);t=wb.prototype;t.da=i;t.X=j;t.addEventListener=function(a,b,c,d){ob(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){rb(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=R;if(b in c){if(w(a))a=new L(a,this);else if(a instanceof L)a.target=a.target||this;else{var d=a,a=new L(b,this);Ka(a,d)}var d=1,f,c=c[b],b=i in c,e;if(b){f=[];for(e=this;e;e=e.X)f.push(e);e=c[i];e.f=e.b;for(var g=f.length-1;!a.n&&0<=g&&e.f;g--)a.currentTarget=f[g],d&=T(e,f[g],a.type,i,a)&&a.I!=k}if(k in c)if(e=c[k],e.f=e.b,b)for(g=0;!a.n&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=T(e,f[g],a.type,k,a)&&a.I!=k;else for(f=this;!a.n&&f&&e.f;f=f.X)a.currentTarget=
f,d&=T(e,f,a.type,k,a)&&a.I!=k;a=Boolean(d)}else a=i;return a};t.i=function(){wb.Y.i.call(this);ub(this);this.X=j};var xb=u.window;function yb(a){if("function"==typeof a.A)return a.A();if(w(a))return a.split("");if(ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)}function zb(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ia(a)||w(a))E(a,b,c);else{var d;if("function"==typeof a.R)d=a.R();else if("function"!=typeof a.A)if(ia(a)||w(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=Ia(a);else d=h;for(var f=yb(a),e=f.length,g=0;g<e;g++)b.call(c,f[g],d&&d[g],a)}};function Ab(a,b){this.v={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Ab?(c=a.R(),d=a.A()):(c=Ia(a),d=Ha(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}t=Ab.prototype;t.b=0;t.Ma=0;t.A=function(){Bb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.v[this.c[b]]);return a};t.R=function(){Bb(this);return this.c.concat()};
function Bb(a){if(a.b!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];Object.prototype.hasOwnProperty.call(a.v,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.b!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],Object.prototype.hasOwnProperty.call(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}t.set=function(a,b){Object.prototype.hasOwnProperty.call(this.v,a)||(this.b++,this.c.push(a),this.Ma++);this.v[a]=b};function Ob(){}Ob.prototype.Z=j;function Pb(a){var b;if(!(b=a.Z))b={},Qb(a)&&(b[0]=i,b[1]=i),b=a.Z=b;return b};var Rb;function Sb(){}B(Sb,Ob);function Tb(a){return(a=Qb(a))?new ActiveXObject(a):new XMLHttpRequest}Sb.prototype.U=j;
function Qb(a){if(!a.U&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.U=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.U}Rb=new Sb;function Ub(a){return Vb(a||arguments.callee.caller,[])}
function Vb(a,b){var c=[];if(0<=Ba(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Wb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=""+e;break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Wb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Vb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Wb(a){if(U[a])return U[a];a=""+a;if(!U[a]){var b=/function ([^\(]+)/.exec(a);U[a]=b?b[1]:"[Anonymous]"}return U[a]}var U={};function V(a,b,c,d,f){this.reset(a,b,c,d,f)}V.prototype.Ja=0;V.prototype.ja=j;V.prototype.ia=j;var Xb=0;V.prototype.reset=function(a,b,c,d,f){this.Ja="number"==typeof f?f:Xb++;this.Va=d||na();this.t=a;this.Ea=b;this.Sa=c;delete this.ja;delete this.ia};V.prototype.ta=function(a){this.t=a};function W(a){this.Fa=a}W.prototype.H=j;W.prototype.t=j;W.prototype.N=j;W.prototype.ka=j;function X(a,b){this.name=a;this.value=b}X.prototype.toString=function(){return this.name};var Yb=new X("SEVERE",1E3),Zb=new X("WARNING",900),$b=new X("CONFIG",700),ac=new X("FINE",500);W.prototype.getParent=function(){return this.H};W.prototype.ta=function(a){this.t=a};function bc(a){if(a.t)return a.t;if(a.H)return bc(a.H);Aa("Root logger has no level set.");return j}
W.prototype.log=function(a,b,c){if(a.value>=bc(this).value){a=this.Ca(a,b,c);b="log:"+a.Ea;u.console&&(u.console.timeStamp?u.console.timeStamp(b):u.console.markTimeline&&u.console.markTimeline(b));u.msWriteProfilerMark&&u.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.ka)for(var f=0,e=h;e=c.ka[f];f++)e(d);b=b.getParent()}}};
W.prototype.Ca=function(a,b,c){var d=new V(a,""+b,this.Fa);if(c){d.ja=c;var f;var e=arguments.callee.caller;try{var g;var n=ga("window.location.href");if(w(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:n,stack:"Not available"};else{var q,l,r=k;try{q=c.lineNumber||c.Ra||"Not available"}catch(m){q="Not available",r=i}try{l=c.fileName||c.filename||c.sourceURL||n}catch(x){l="Not available",r=i}g=r||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:q,
fileName:l,stack:c.stack||"Not available"}:c}f="Message: "+ra(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+ra(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ra(Ub(e)+"-> ")}catch(o){f="Exception trying to expose exception! You win, we lose. "+o}d.ia=f}return d};function Y(a,b){a.log(ac,b,h)}var cc={},dc=j;
function ec(a){dc||(dc=new W(""),cc[""]=dc,dc.ta($b));var b;if(!(b=cc[a])){b=new W(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=ec(a.substr(0,c));if(!c.N)c.N={};c.N[d]=b;b.H=c;cc[a]=b}return b};function fc(a){this.headers=new Ab;this.L=a||j}B(fc,wb);fc.prototype.e=ec("goog.net.XhrIo");var gc=/^https?:?$/i;t=fc.prototype;t.h=k;t.a=j;t.K=j;t.s="";t.na="";t.q=0;t.r="";t.Q=k;t.B=k;t.V=k;t.j=k;t.J=0;t.l=j;t.sa="";t.Na=k;
t.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request");b=b?b.toUpperCase():"GET";this.s=a;this.r="";this.q=0;this.na=b;this.Q=k;this.h=i;this.a=this.L?Tb(this.L):Tb(Rb);this.K=this.L?Pb(this.L):Pb(Rb);this.a.onreadystatechange=A(this.qa,this);try{Y(this.e,Z(this,"Opening Xhr")),this.V=i,this.a.open(b,a,i),this.V=k}catch(f){Y(this.e,Z(this,"Error opening Xhr: "+f.message));hc(this,f);return}var a=c||"",e=new Ab(this.headers);d&&zb(d,function(a,b){e.set(b,
a)});"POST"==b&&!Object.prototype.hasOwnProperty.call(e.v,"Content-Type")&&e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");zb(e,function(a,b){this.a.setRequestHeader(b,a)},this);if(this.sa)this.a.responseType=this.sa;if("withCredentials"in this.a)this.a.withCredentials=this.Na;try{if(this.l)xb.clearTimeout(this.l),this.l=j;if(0<this.J)Y(this.e,Z(this,"Will abort after "+this.J+"ms if incomplete")),this.l=xb.setTimeout(A(this.La,this),this.J);Y(this.e,Z(this,"Sending request"));
this.B=i;this.a.send(a);this.B=k}catch(g){Y(this.e,Z(this,"Send error: "+g.message)),hc(this,g)}};t.La=function(){if("undefined"!=typeof aa&&this.a)this.r="Timed out after "+this.J+"ms, aborting",this.q=8,Y(this.e,Z(this,this.r)),this.dispatchEvent("timeout"),this.abort(8)};function hc(a,b){a.h=k;if(a.a)a.j=i,a.a.abort(),a.j=k;a.r=b;a.q=5;ic(a);jc(a)}function ic(a){if(!a.Q)a.Q=i,a.dispatchEvent("complete"),a.dispatchEvent("error")}
t.abort=function(a){if(this.a&&this.h)Y(this.e,Z(this,"Aborting")),this.h=k,this.j=i,this.a.abort(),this.j=k,this.q=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),jc(this)};t.i=function(){if(this.a){if(this.h)this.h=k,this.j=i,this.a.abort(),this.j=k;jc(this,i)}fc.Y.i.call(this)};t.qa=function(){!this.V&&!this.B&&!this.j?this.Ga():kc(this)};t.Ga=function(){kc(this)};
function kc(a){if(a.h&&"undefined"!=typeof aa)if(a.K[1]&&4==$(a)&&2==lc(a))Y(a.e,Z(a,"Local request error detected and ignored"));else if(a.B&&4==$(a))xb.setTimeout(A(a.qa,a),0);else if(a.dispatchEvent("readystatechange"),4==$(a)){Y(a.e,Z(a,"Request complete"));a.h=k;var b;a:switch(lc(a)){case 0:b=w(a.s)?a.s.match(ib)[1]||j:a.s.Pa();b=!(b?gc.test(b):self.location?gc.test(self.location.protocol):1);break a;case 200:case 201:case 202:case 204:case 304:case 1223:b=i;break a;default:b=k}if(b)a.dispatchEvent("complete"),
a.dispatchEvent("success");else{a.q=6;var c;try{c=2<$(a)?a.a.statusText:""}catch(d){Y(a.e,"Can not get status: "+d.message),c=""}a.r=c+" ["+lc(a)+"]";ic(a)}jc(a)}}function jc(a,b){if(a.a){var c=a.a,d=a.K[0]?ha:j;a.a=j;a.K=j;if(a.l)xb.clearTimeout(a.l),a.l=j;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(f){a.e.log(Yb,"Problem encountered resetting onreadystatechange: "+f.message,h)}}}function $(a){return a.a?a.a.readyState:0}
function lc(a){try{return 2<$(a)?a.a.status:-1}catch(b){return a.e.log(Zb,"Can not get status: "+b.message,h),-1}}t.getResponseHeader=function(a){return this.a&&4==$(this)?this.a.getResponseHeader(a):h};function Z(a,b){return b+" ["+a.na+" "+a.s+" "+lc(a)+"]"};function mc(){return i};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var nc=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!w(a))return[a];if(w(c)&&(c=w(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;N=c.contentType&&"application/xml"==c.contentType||Ta&&(c.doctype||"[object XMLDocument]"==e.toString())||!!e&&(H?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.F?e:b(e)}function b(a){if(a&&a.F)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;
C++;if(H&&N){var c=C+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(H&&a.wa)try{for(d=1;e=a[d];d++)ya(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=C);for(d=1;e=a[d];d++)a[d]._zipIdx!=C&&b.push(e),e._zipIdx=C}return b}function c(a,b){if(!b)return 1;var c=sc(a);return!b[c]?b[c]=1:0}function d(a,b){if(Eb){var c=Fb[a];if(c&&!b)return c}if(c=Gb[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");0<=a.indexOf("#")&&
e&&(b=i);if(Eb&&!b&&-1==">~+".indexOf(c)&&(!H||-1==a.indexOf(":"))&&!(Hb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var g=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Fb[a]=function(b){try{if(!(9==b.nodeType||e))throw"";var c=b.querySelectorAll(g);H?c.wa=i:c.F=i;return c}catch(f){return d(a,i)(b)}}}var Db=a.split(/\s*,\s*/);return Gb[a]=2>Db.length?f(a):function(a){for(var b=0,c=[],d;d=Db[b++];)c=c.concat(f(d)(a));return c}}function f(a){var b=Ib(qa(a));if(1==
b.length){var c=e(b[0]);return function(a){if(a=c(a,[]))a.F=i;return a}}return function(a){for(var a=da(a),c,d,f=b.length,Cb,g,Ra=0;Ra<f;Ra++){g=[];c=b[Ra];d=a.length-1;if(0<d)Cb={},g.F=i;d=e(c);for(var Jb=0;c=a[Jb];Jb++)d(c,g,Cb);if(!g.length)break;a=g}return g}}function e(a){var b=Kb[a.o];if(b)return b;var c=a.la,c=c?c.G:"",d=l(a,{m:1}),e="*"==a.d,f=document.getElementsByClassName;if(c){f={m:1};if(e)f.d=1;d=l(a,f);"+"==c?b=q(d):"~"==c?b=n(d):">"==c&&(b=g(d))}else if(a.id)d=!a.oa&&e?mc:l(a,{m:1,
id:1}),b=function(b,c){var e;e=b?new J(9==b.nodeType?b:b.ownerDocument||b.document):Da||(Da=new J);var f=a.id;if(f=(e=w(f)?e.O.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&!(f==b);)f=f.parentNode;f=!!f}if(f)return da(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(""+f)&&a.g.length&&!Hb)var d=l(a,{m:1,g:1,id:1}),m=a.g.join(" "),b=function(a,b){for(var c=da(0,b),e,f=0,ca=a.getElementsByClassName(m);e=ca[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.oa?b=function(b,c){for(var d=
da(0,c),e,f=0,ca=b.getElementsByTagName(a.S());e=ca[f++];)d.push(e);return d}:(d=l(a,{m:1,d:1,id:1}),b=function(b,c){for(var e=da(0,c),f,ca=0,g=b.getElementsByTagName(a.S());f=g[ca++];)d(f,b)&&e.push(f);return e});return Kb[a.o]=b}function g(a){a=a||mc;return function(b,d,e){for(var f=0,g=b[Lb];b=g[f++];)ea(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function n(a){return function(b,d,e){for(b=b[fa];b;){if(ea(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[fa]}return d}}function q(a){return function(b,
d,e){for(;b=b[fa];)if(!za||ya(b)){(!e||c(b,e))&&a(b)&&d.push(b);break}return d}}function l(a,b){if(!a)return mc;var b=b||{},c=j;b.m||(c=O(c,ya));b.d||"*"!=a.d&&(c=O(c,function(b){return b&&b.tagName==a.S()}));b.g||E(a.g,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=O(c,function(a){return d.test(a.className)});c.Oa=b});b.k||E(a.k,function(a){var b=a.name;Sa[b]&&(c=O(c,Sa[b](b,a.value)))});b.w||E(a.w,function(a){var b,d=a.M;a.type&&Mb[a.type]?b=Mb[a.type](d,a.W):d.length&&(b=tc(d));b&&(c=
O(c,b))});b.id||a.id&&(c=O(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=mc);return c}function r(a){return x(a)%2}function m(a){return!(x(a)%2)}function x(a){var b=a.parentNode,c=0,d=b[Lb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[fa])if(ea(b))b._i=++c,a===b&&(e=c);return e}function o(a){for(;a=a[fa];)if(ea(a))return k;return i}function Nb(a){for(;a=a[uc];)if(ea(a))return k;return i}function P(a,
b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(N?a.getAttribute(b):a.getAttribute(b,2))||""}function ya(a){return 1==a.nodeType}function O(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Ib(a){function b(){if(0<=n)p.id=c(n,s).replace(/\\/g,""),n=-1;if(0<=q){var a=q==s?j:c(q,s);0>">~+".indexOf(a)?p.d=a:p.G=a;q=-1}0<=m&&(p.g.push(c(m+1,s).replace(/\\/g,"")),m=-1)}function c(b,d){return qa(a.slice(b,
d))}for(var a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ",d=[],e=-1,f=-1,g=-1,l=-1,m=-1,n=-1,q=-1,r="",o="",x,s=0,C=a.length,p=j,y=j;r=o,o=a.charAt(s),s<C;s++)if("\\"!=r)if(p||(x=s,p={o:j,k:[],w:[],g:[],d:j,G:j,id:j,S:function(){return N?this.Ha:this.d}},q=s),0<=e)if("]"==o){y.M?y.W=c(g||e+1,s):y.M=c(e+1,s);if((e=y.W)&&('"'==e.charAt(0)||"'"==e.charAt(0)))y.W=e.slice(1,-1);p.w.push(y);y=j;e=g=-1}else{if("="==o)g=0<="|~^$*".indexOf(r)?r:"",y.type=g+o,y.M=c(e+1,s-g.length),g=s+1}else if(0<=f){if(")"==
o){if(0<=l)y.value=c(f+1,s);l=f=-1}}else if("#"==o)b(),n=s+1;else if("."==o)b(),m=s;else if(":"==o)b(),l=s;else if("["==o)b(),e=s,y={};else if("("==o)0<=l&&(y={name:c(l+1,s),value:j},p.k.push(y)),f=s;else if(" "==o&&r!=o){b();0<=l&&p.k.push({name:c(l+1,s)});p.oa=p.k.length||p.w.length||p.g.length;p.Ua=p.o=c(x,s);p.Ha=p.d=p.G?j:p.d||"*";if(p.d)p.d=p.d.toUpperCase();if(d.length&&d[d.length-1].G)p.la=d.pop(),p.o=p.la.o+" "+p.o;d.push(p);p=j}return d}function da(a,b){var c=b||[];a&&c.push(a);return c}
var Hb=Va&&"BackCompat"==document.compatMode,Lb=document.firstChild.children?"children":"childNodes",N=k,Mb={"*=":function(a,b){return function(c){return 0<=P(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==P(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+P(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+P(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+P(c,a);return c==
b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return P(c,a)==b}}},za="undefined"==typeof document.firstChild.nextElementSibling,fa=!za?"nextElementSibling":"nextSibling",uc=!za?"previousElementSibling":"previousSibling",ea=za?ya:mc,Sa={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Nb},"last-child":function(){return o},"only-child":function(){return function(a){return!Nb(a)||!o(a)?k:i}},empty:function(){return function(a){for(var b=
a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return k}return i}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=Ib(b)[0],d={m:1};if("*"!=c.d)d.d=1;if(!c.g.length)d.g=1;var e=l(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return r;if("even"==b)return m;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],
10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=x(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var l=parseInt(b,10);return function(a){return x(a)==l}}},tc=H?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return N?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},Kb={},Gb={},Fb={},Eb=!!document.querySelectorAll&&
(!Va||eb("526")),C=0,sc=H?function(a){return N?a.getAttribute("_uid")||a.setAttribute("_uid",++C)||C:a.uniqueID}:function(a){return a._uid||(a._uid=++C)};a.k=Sa;return a}();ba("goog.dom.query",nc);ba("goog.dom.query.pseudos",nc.k);var oc;a:{for(var pc=document.getElementsByTagName("link"),qc=0;qc<pc.length;qc++)if(pc.item(qc).href.match(/std/)){oc=pc.item(qc).href.replace(/grn\/html\/std.css.*/,"cbmw5/");break a}oc=k}function rc(a,b){this.Ba="/m/mw.cgi?page=ApiNotificationSummary&ct=json&oencoding=UTF-8&ver=1&num="+b;this.P=a}
rc.prototype={Da:function(){var a=new fc;ob(a,"success",function(a){var c=k,a=a.target,d=this.fa();try{var f;f=a.a?hb(a.a.responseText):h;"ok"==f.status?this.Ka(f,this.P):(c=i,d=this.ga(f.code))}catch(e){c=i,a.getResponseHeader("X-CybozuLogin")&&(d=this.ga(10102))}c&&this.ua(d,this.P)}.bind(this));ob(a,"error",function(){this.ua(this.fa(),this.P)}.bind(this));a.send(this.Ba,"POST")},Ka:function(a,b){var c=k;b.Qa="";for(var d=0;d<a.Workspaces.length;d++)for(var f=0;f<a.Workspaces[d].mails.length;f++)if(0<
a.Workspaces[d].mails[f].assigned.count+a.Workspaces[d].mails[f].todos.count){c||(c=i);var e=a.Workspaces[d].mails[f],g=document.createElement("div");g.style.marginBottom="3px";g.appendChild(this.za());g.appendChild(this.aa(e.url,e.name));g.appendChild(document.createTextNode("\u306b"));0<e.assigned.count&&g.appendChild(this.ca(e.assigned,"\u62c5\u5f53\u30e1\u30fc\u30eb\u304c "));0<e.todos.count&&(0<e.assigned.count&&g.appendChild(document.createTextNode("\u3001")),g.appendChild(this.ca(e.todos,"\u78ba\u8a8d\u30e1\u30fc\u30eb\u304c ")));
g.appendChild(document.createTextNode(" \u3042\u308a\u307e\u3059\u3002"));b.appendChild(g)}if(!c)if("textContent"in b)b.textContent="\u304a\u77e5\u3089\u305b\u306f\u3042\u308a\u307e\u305b\u3093";else if(b.firstChild&&3==b.firstChild.nodeType){for(;b.lastChild!=b.firstChild;)b.removeChild(b.lastChild);b.firstChild.data="\u304a\u77e5\u3089\u305b\u306f\u3042\u308a\u307e\u305b\u3093"}else{for(;c=b.firstChild;)b.removeChild(c);b.appendChild((9==b.nodeType?b:b.ownerDocument||b.document).createTextNode("\u304a\u77e5\u3089\u305b\u306f\u3042\u308a\u307e\u305b\u3093"))}},
ca:function(a,b){var c=this.aa(a.url,b);c.appendChild(this.xa(a.count));c.appendChild(document.createTextNode(" \u4ef6"));return c},za:function(){return this.ba(oc+"image/notify_mailwise16.png")},ya:function(){return this.ba(oc+"image/notify_mailwise16_e.png")},ba:function(a){var b=document.createElement("img");b.src=a;b.width=16;b.height=16;return b},aa:function(a,b){var c=document.createElement("a");c.href=a;c.target="_blank";c.appendChild(document.createTextNode(b));return c},xa:function(a){var b=
document.createElement("b");b.appendChild(document.createTextNode(a));return b},ua:function(a,b){var c=document.createElement("div");c.appendChild(this.ya());c.appendChild(document.createTextNode(a));b.appendChild(c)},va:"\u60c5\u5831\u306e\u53d6\u5f97\u306b\u5931\u6557\u3057\u307e\u3057\u305f",fa:function(){return this.va+"\u3002"},ga:function(a){return this.va+"\uff08\u30a8\u30e9\u30fc\u756a\u53f7:"+a+"\uff09\u3002"}};
ba("grn.mailwise.portlet.draw",function(){E(nc(".mailwise_portlet_main"),function(a,b){0<=Ba(Ea(a),"mailwise_portlet_main_done")||(Fa(a,"mailwise_portlet_main_done"),(new rc(a,b)).Da())})});})();
